DROP TABLE "Tm_Approval";
CREATE COLUMN TABLE "Tm_Approval"
(
    "Id" INTEGER CS_INT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
    "TransType"     NVARCHAR(50),
    "FormCode"      NVARCHAR(50),
    "ApprovalName"  NVARCHAR(50),
    "IsActive"      CHAR(1) CS_FIXEDSTRING,
    "CreatedDate"   LONGDATE CS_LONGDATE,
    "CreatedUser"   INTEGER CS_INT,
    "ModifiedDate"  LONGDATE CS_LONGDATE,
    "ModifiedUser"  INTEGER CS_INT,
    PRIMARY KEY ("Id")
)
UNLOAD PRIORITY 5
AUTO MERGE;

DROP TABLE "Tm_Approval_Role";
CREATE COLUMN TABLE "Tm_Approval_Role"
(
    "Id" INTEGER CS_INT,
    "DetId" INTEGER CS_INT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
    "RoleId" INTEGER CS_INT,
    "IsTick" CHAR(1) CS_FIXEDSTRING,
    "CreatedDate" LONGDATE CS_LONGDATE,
    "CreatedUser" INTEGER CS_INT,
    "ModifiedDate" LONGDATE CS_LONGDATE,
    "ModifiedUser" INTEGER CS_INT,
    PRIMARY KEY ("DetId")
)
UNLOAD PRIORITY 5
AUTO MERGE;

DROP TABLE "Tm_Approval_User";
CREATE COLUMN TABLE "Tm_Approval_User"
(
    "Id" INTEGER CS_INT,
    "DetId" INTEGER CS_INT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
    "UserId" INTEGER CS_INT,
    "IsTick" CHAR(1) CS_FIXEDSTRING,
    "CreatedDate" LONGDATE CS_LONGDATE,
    "CreatedUser" INTEGER CS_INT,
    "ModifiedDate" LONGDATE CS_LONGDATE,
    "ModifiedUser" INTEGER CS_INT,
    PRIMARY KEY ("DetId")
)
UNLOAD PRIORITY 5
AUTO MERGE;

DROP TABLE "Tm_ApprovalStage"
CREATE COLUMN TABLE "Tm_ApprovalStage"
(
    "Id" INTEGER CS_INT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
    "TransType" NVARCHAR(50),
    "StageName" VARCHAR(50),
    "Description" NVARCHAR(100),
    "MinApprove" INTEGER CS_INT,
    "MinReject" INTEGER CS_INT,
    "CreatedDate" LONGDATE CS_LONGDATE,
    "CreatedUser" INTEGER CS_INT,
    "ModifiedDate" LONGDATE CS_LONGDATE,
    "ModifiedUser" INTEGER CS_INT,
    PRIMARY KEY ("Id")
)
UNLOAD PRIORITY 5
AUTO MERGE;

DROP TABLE "Tm_ApprovalStage_Role";
CREATE COLUMN TABLE "Tm_ApprovalStage_Role"
(
    "Id" INTEGER CS_INT,
    "DetId" INTEGER CS_INT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
    "RoleId" INTEGER CS_INT,
    "IsTick" CHAR(1) CS_FIXEDSTRING,
    "CreatedDate" LONGDATE CS_LONGDATE,
    "CreatedUser" INTEGER CS_INT,
    "ModifiedDate" LONGDATE CS_LONGDATE,
    "ModifiedUser" INTEGER CS_INT,
    PRIMARY KEY ("DetId")
)
UNLOAD PRIORITY 5
AUTO MERGE;

DROP TABLE "Tm_ApprovalStage_User";
CREATE COLUMN TABLE "Tm_ApprovalStage_User"
(
    "Id" INTEGER CS_INT,
    "DetId" INTEGER CS_INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "UserId" INTEGER CS_INT,
    "IsTick" CHAR(1) CS_FIXEDSTRING,
    "CreatedDate" SECONDDATE CS_SECONDDATE,
    "CreatedUser" INTEGER CS_INT,
    "ModifiedDate" SECONDDATE CS_SECONDDATE,
    "ModifiedUser" INTEGER CS_INT,
    PRIMARY KEY ("DetId")
)
UNLOAD PRIORITY 5
AUTO MERGE;

DROP TABLE "Tm_ApprovalTemplate";
CREATE COLUMN TABLE "Tm_ApprovalTemplate"
(
    "Id" INTEGER CS_INT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
    "TransType" NVARCHAR(50),
    "TemplateName" VARCHAR(50),
    "ObjectCode" VARCHAR(50),
    "IsActive" CHAR(1) CS_FIXEDSTRING,
    "Sql" CLOB MEMORY THRESHOLD 1000,
    "CreatedDate" LONGDATE CS_LONGDATE,
    "CreatedUser" INTEGER CS_INT,
    "ModifiedDate" LONGDATE CS_LONGDATE,
    "ModifiedUser" INTEGER CS_INT,
    PRIMARY KEY ("Id")
)
UNLOAD PRIORITY 5
AUTO MERGE;

DROP TABLE "Tm_ApprovalTemplate_Position";
CREATE COLUMN TABLE "Tm_ApprovalTemplate_Position"
(
    "Id" INTEGER CS_INT,
    "DetId" INTEGER CS_INT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
    "Position" NVARCHAR(50),
    "IsTick" CHAR(1) CS_FIXEDSTRING,
    "CreatedDate" LONGDATE CS_LONGDATE,
    "CreatedUser" INTEGER CS_INT,
    "ModifiedDate" LONGDATE CS_LONGDATE,
    "ModifiedUser" INTEGER CS_INT,
    PRIMARY KEY ("DetId")
)
UNLOAD PRIORITY 5
AUTO MERGE;

DROP TABLE "Tm_ApprovalTemplate_Role";
CREATE COLUMN TABLE "Tm_ApprovalTemplate_Role"
(
    "Id" INTEGER CS_INT,
    "DetId" INTEGER CS_INT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
    "RoleId" INTEGER CS_INT,
    "IsTick" CHAR(1) CS_FIXEDSTRING,
    "CreatedDate" LONGDATE CS_LONGDATE,
    "CreatedUser" INTEGER CS_INT,
    "ModifiedDate" LONGDATE CS_LONGDATE,
    "ModifiedUser" INTEGER CS_INT,
    PRIMARY KEY ("DetId")
)
UNLOAD PRIORITY 5
AUTO MERGE;

DROP TABLE "Tm_ApprovalTemplate_Stage";
CREATE COLUMN TABLE "Tm_ApprovalTemplate_Stage"
(
    "Id" INTEGER CS_INT,
    "DetId" INTEGER CS_INT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
    "StageId" INTEGER CS_INT,
    "Step" INTEGER CS_INT,
    "SortCode" NVARCHAR(50),
    "CreatedDate" LONGDATE CS_LONGDATE,
    "CreatedUser" INTEGER CS_INT,
    "ModifiedDate" LONGDATE CS_LONGDATE,
    "ModifiedUser" INTEGER CS_INT,
    PRIMARY KEY ("DetId")
)
UNLOAD PRIORITY 5
AUTO MERGE;

DROP TABLE "Tm_ApprovalTemplate_User";
CREATE COLUMN TABLE "Tm_ApprovalTemplate_User"
(
    "Id" INTEGER CS_INT,
    "DetId" BIGINT CS_FIXED GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
    "UserId" INTEGER CS_INT,
    "IsTick" NVARCHAR(1),
    "CreatedDate" LONGDATE CS_LONGDATE,
    "CreatedUser" INTEGER CS_INT,
    "ModifiedDate" LONGDATE CS_LONGDATE,
    "ModifiedUser" INTEGER CS_INT,
    PRIMARY KEY ("DetId")
)
UNLOAD PRIORITY 5
AUTO MERGE;

DROP TABLE "Tp_Approval";
CREATE COLUMN TABLE "Tp_Approval"
(
    "Id" INTEGER CS_INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "TransType" NVARCHAR(50),
    "TemplateId" INTEGER CS_INT,
    "CurrentStep" INTEGER CS_INT,
    "ObjectId" NVARCHAR(255),
    "ObjectCode" NVARCHAR(50),
    "Status" NVARCHAR(50),
    "FlagNo" NVARCHAR(50),
    "CreatedDate" SECONDDATE CS_SECONDDATE,
    "CreatedUser" INTEGER CS_INT,
    "ModifiedDate" SECONDDATE CS_SECONDDATE,
    "ModifiedUser" INTEGER CS_INT,
    PRIMARY KEY ("Id")
)
UNLOAD PRIORITY 5
AUTO MERGE;

DROP TABLE "Tm_ApprovalStage";
CREATE COLUMN TABLE "Tm_ApprovalStage"
(
    "Id" INTEGER CS_INT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
    "TransType" NVARCHAR(50),
    "StageName" VARCHAR(50),
    "Description" NVARCHAR(100),
    "MinApprove" INTEGER CS_INT,
    "MinReject" INTEGER CS_INT,
    "CreatedDate" LONGDATE CS_LONGDATE,
    "CreatedUser" INTEGER CS_INT,
    "ModifiedDate" LONGDATE CS_LONGDATE,
    "ModifiedUser" INTEGER CS_INT,
    PRIMARY KEY ("Id")
)
UNLOAD PRIORITY 5
AUTO MERGE;

CREATE COLUMN TABLE "Ts_ObjectApproval" (
  "ObjectCode" NVARCHAR(50) NOT NULL, 
  "ObjectName" NVARCHAR(200), 
  "Sort" NVARCHAR(50), 
  PRIMARY KEY ("ObjectCode")
) UNLOAD PRIORITY 5 AUTO MERGE
;

DROP TABLE "Tm_User_Routing";
CREATE COLUMN TABLE "Tm_User_Routing" (
  "Id" INTEGER CS_INT, 
  "DetId" INTEGER CS_INT GENERATED BY DEFAULT AS IDENTITY, 
  "RoutingCode" NVARCHAR(100) CS_FIXEDSTRING, 
  "RoutingName" NVARCHAR(100) CS_FIXEDSTRING, 
  "IsTick" CHAR(1) CS_FIXEDSTRING, 
  "CreatedDate" LONGDATE CS_LONGDATE, 
  "CreatedUser" INTEGER CS_INT, 
  "ModifiedDate" LONGDATE CS_LONGDATE, 
  "ModifiedUser" INTEGER CS_INT, 
  PRIMARY KEY ("DetId")
) UNLOAD PRIORITY 5 AUTO MERGE
;

DROP TABLE "Tm_Position" ;
CREATE COLUMN TABLE "Tm_Position" (
  "Id" INTEGER CS_INT GENERATED BY DEFAULT AS IDENTITY, 
  "PositionName" NVARCHAR(100) CS_FIXEDSTRING, 
  "IsActive" CHAR(1) CS_FIXEDSTRING, 
  "CreatedDate" LONGDATE CS_LONGDATE, 
  "CreatedUser" INTEGER CS_INT, 
  "ModifiedDate" LONGDATE CS_LONGDATE, 
  "ModifiedUser" INTEGER CS_INT, 
  PRIMARY KEY ("Id")
) UNLOAD PRIORITY 5 AUTO MERGE
;


DROP TABLE "Tx_StockOpname";
CREATE COLUMN TABLE "Tx_StockOpname"(
    "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "TransType" NVARCHAR(50),
    "TransNo" NVARCHAR(50),
    
    "DocEntry" INT,
    "DocNum" NVARCHAR(50),
    "TransDate" TIMESTAMP,
    "PostingDate" TIMESTAMP,

    "WhsCode" NVARCHAR(50),
    "WhsName" VARCHAR(100),

    "Status" NVARCHAR(50),
    "ApprovalStatus" NVARCHAR(50),
    "IsAfterPosted" CHAR(1),
    "Comments" NVARCHAR(254),
    "CancelReason" NVARCHAR(254),    

    "IsApproval" CHAR(1),
    "ApprovalMessages" NVARCHAR(254),

    "CreatedDate" TIMESTAMP,
    "CreatedUser" INTEGER,
    "ModifiedDate" TIMESTAMP,
    "ModifiedUser" INTEGER
);

DROP TABLE "Tx_StockOpname_Item";
CREATE COLUMN TABLE "Tx_StockOpname_Item" (
    "Id" BIGINT,
    "DetId" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    "ItemCode" NVARCHAR(50),
    "ItemName" NVARCHAR(200),
    "WhsCode" NVARCHAR(50),

    "Quantity" DECIMAL(21,2),
    "QtyVariance" DECIMAL(21,2),	
    "UomEntry" INTEGER,
    "Uom" NVARCHAR(50),
    "AcctCode" NVARCHAR(100),
    "AcctName" NVARCHAR(100),
	
    "UnitPriceTc" DECIMAL(21,2),
    "LineTotal" DECIMAL(21,2),
    
    "FreeText" NVARCHAR(254),
    "CreatedDate" TIMESTAMP,
    "CreatedUser" INTEGER,
    "ModifiedDate" TIMESTAMP,
    "ModifiedUser" INTEGER
);

DROP TABLE "Tx_StockOpname_Approval";
CREATE COLUMN TABLE "Tx_StockOpname_Approval"
(
    "Id" INTEGER CS_INT,
    "DetId" INTEGER CS_INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "StageId" INTEGER CS_INT,
    "UserId" INTEGER CS_INT,
    "Step" INTEGER CS_INT,
    "Status" NVARCHAR(50),
    "Comments" NVARCHAR(1000),
    "ActionDate" SECONDDATE CS_SECONDDATE,
    "CreatedDate" SECONDDATE CS_SECONDDATE,
    "CreatedUser" INTEGER CS_INT,
    "ModifiedDate" SECONDDATE CS_SECONDDATE,
    "ModifiedUser" INTEGER CS_INT,
    PRIMARY KEY ("DetId")
)
;

DROP TABLE "Tx_ProcessCard";
CREATE COLUMN TABLE "Tx_ProcessCard"(
    "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "TransType" NVARCHAR(50),
    "TransNo" NVARCHAR(50),

    "DocEntry" INT,
    "DocNum" NVARCHAR(50),
    "TransDate" TIMESTAMP,
    "PostingDate" TIMESTAMP,
    "DueDate" TIMESTAMP,
    "SerialNumber" NVARCHAR(200),

    "ContractNo" NVARCHAR(100),

    "CardCode" NVARCHAR(15),
    "CardName" NVARCHAR(200),
    "ItemCode" NVARCHAR(50),
    "ItemName" NVARCHAR(200),
    "Quantity" DECIMAL(21,2), 
    "Comments" NVARCHAR(254),
    "CancelReason" NVARCHAR(254),  

    "IsApproval" CHAR(1),
    "ApprovalStatus" NVARCHAR(50),
    "ApprovalMessages" NVARCHAR(254),

    "Status" NVARCHAR(50),
    "IsAfterPosted" CHAR(1),

    "CreatedDate"   LONGDATE CS_LONGDATE,
    "CreatedUser"   INTEGER CS_INT,
    "ModifiedDate"  LONGDATE CS_LONGDATE,
    "ModifiedUser"  INTEGER CS_INT 
)
;

DROP TABLE "Tx_ProcessCard_Detail";
CREATE COLUMN TABLE "Tx_ProcessCard_Detail" (
    "Id" BIGINT ,
    "DetId" BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL PRIMARY KEY,

    "RoutingCode" NVARCHAR(100),
    "RoutingName" NVARCHAR(100),
    "RoutingStatus" NVARCHAR(20),

    "OperatorId" INTEGER, 

    "ProcessingDate" TIMESTAMP,
    "EndDate" TIMESTAMP,

    "MachineId" INTEGER,
    "MachineName" NVARCHAR(100),

    "PracticeHours" TIME,
    "ActualHours" TIME,

    "LineStatus" NVARCHAR(20),
    "Comments" NVARCHAR(254),

    "CreatedDate" TIMESTAMP,
    "CreatedUser" INTEGER,

    "ModifiedDate" TIMESTAMP,
    "ModifiedUser" INTEGER
);

DROP TABLE "Tx_ProcessCard_Approval";
CREATE COLUMN TABLE "Tx_ProcessCard_Approval"
(
    "Id" INTEGER CS_INT,
    "DetId" INTEGER CS_INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "StageId" INTEGER CS_INT,
    "UserId" INTEGER CS_INT,
    "Step" INTEGER CS_INT,
    "Status" NVARCHAR(50),
    "Comments" NVARCHAR(1000),
    "ActionDate" SECONDDATE CS_SECONDDATE,
    "CreatedDate" SECONDDATE CS_SECONDDATE,
    "CreatedUser" INTEGER CS_INT,
    "ModifiedDate" SECONDDATE CS_SECONDDATE,
    "ModifiedUser" INTEGER CS_INT,
    PRIMARY KEY ("DetId")
)
;
