DROP TABLE "Tx_AdjustmentIn";
CREATE COLUMN TABLE "Tx_AdjustmentIn" (
    "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    "TransType" NVARCHAR(50),
    "TransNo" NVARCHAR(50),
    "TransDate" TIMESTAMP,
    "PostingDate" TIMESTAMP,
    "AdjustmentTypeCode" NVARCHAR(100),
    "AdjustmentTypeName" NVARCHAR(100),    

    "PillarsCode" NVARCHAR(10),
    "PillarsName" NVARCHAR(50),
    "ClassCode" NVARCHAR(10),
    "ClassName" NVARCHAR(50),
    "SubClass1Code" NVARCHAR(10),
    "SubClass1Name" NVARCHAR(50),
    "SubClass2Code" NVARCHAR(10),
    "SubClass2Name" NVARCHAR(50),
    "ProjectCode" NVARCHAR(50),
    "ProjectName" NVARCHAR(100),

    "Status" NVARCHAR(50),
    "ApprovalStatus" NVARCHAR(50),
    "IsAfterPosted" CHAR(1),
    "IsOpeningBalance" CHAR(1),
    "DocEntry" INTEGER,
    "Comments" NVARCHAR(200),
    "ScanDeviceId" NVARCHAR(1000),
    "WhsCode" NVARCHAR(50),
    "CancelReason" NVARCHAR(500),

    "IsApproval" CHAR(1),
    "ApprovalMessages" NVARCHAR(254),    

    "CreatedDate" TIMESTAMP,
    "CreatedUser" INTEGER,
    "ModifiedDate" TIMESTAMP,
    "ModifiedUser" INTEGER
);


DROP TABLE "Tx_AdjustmentIn_Item";
CREATE COLUMN TABLE "Tx_AdjustmentIn_Item" (
    "Id" BIGINT NOT NULL,
    "DetId" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "ItemCode" NVARCHAR(50),
    "ItemName" NVARCHAR(200),
    "FreeText" NVARCHAR(1000),
    "WhsCode" NVARCHAR(50),

    "PillarsCode" NVARCHAR(10),
    "PillarsName" NVARCHAR(50),
    "ClassCode" NVARCHAR(10),
    "ClassName" NVARCHAR(50),
    "SubClass1Code" NVARCHAR(10),
    "SubClass1Name" NVARCHAR(50),
    "SubClass2Code" NVARCHAR(10),
    "SubClass2Name" NVARCHAR(50),
    "ProjectCode" NVARCHAR(50),
    "ProjectName" NVARCHAR(100),

    "QuantityScan" DECIMAL(21, 2), 
    "QuantityPosted" DECIMAL(21, 2), 
    "LineStatus" NVARCHAR(50),
    "UnitPriceTc" DECIMAL(21, 2),  
    "UomEntry" INT,
    "Uom" NVARCHAR(50),
    "CreatedDate" TIMESTAMP,
    "CreatedUser" INTEGER,
    "ModifiedDate" TIMESTAMP,
    "ModifiedUser" INTEGER
);

DROP TABLE "Tx_AdjustmentIn_Item_Tag";
CREATE COLUMN TABLE "Tx_AdjustmentIn_Item_Tag" (
    "Id" BIGINT,
    "DetId" BIGINT,
    "DetDetId" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    "ItemCode" NVARCHAR(50),
    "ItemName" NVARCHAR(200),
    "TagId" NVARCHAR(200),
    "Quantity" DECIMAL(21,6),
    "EventType" NVARCHAR(100),
    "Status" NVARCHAR(50),
    "PostResultNote" NVARCHAR(500),
    "CreatedDate" TIMESTAMP,
    "CreatedUser" INTEGER,
    "ModifiedDate" TIMESTAMP,
    "ModifiedUser" INTEGER
);

DROP TABLE "Tx_AdjustmentOut";
CREATE COLUMN TABLE "Tx_AdjustmentOut" (
    "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "TransType" NVARCHAR(50),
    "TransNo" NVARCHAR(50),
    "TransDate" TIMESTAMP,
    "PostingDate" TIMESTAMP,
    "AdjustmentTypeCode" NVARCHAR(100),
    "AdjustmentTypeName" NVARCHAR(100),

    "PillarsCode" NVARCHAR(10),
    "PillarsName" NVARCHAR(50),
    "ClassCode" NVARCHAR(10),
    "ClassName" NVARCHAR(50),
    "SubClass1Code" NVARCHAR(10),
    "SubClass1Name" NVARCHAR(50),
    "SubClass2Code" NVARCHAR(10),
    "SubClass2Name" NVARCHAR(50),
    "ProjectCode" NVARCHAR(50),
    "ProjectName" NVARCHAR(100),

    "Status" NVARCHAR(50),    
    "IsAfterPosted" CHAR(1),
    "IsOpeningBalance" CHAR(1),
    "DocEntry" INTEGER,
    "Comments" NVARCHAR(200),
    "ScanDeviceId" NVARCHAR(1000),
    "WhsCode" NVARCHAR(50),
    "CancelReason" NVARCHAR(500),
    "IsApproval" CHAR(1),
    "ApprovalMessages" NVARCHAR(254),

    "CreatedDate" TIMESTAMP,
    "CreatedUser" INTEGER,
    "ModifiedDate" TIMESTAMP,
    "ModifiedUser" INTEGER
);

DROP TABLE "Tx_AdjustmentOut_Item";
CREATE COLUMN TABLE "Tx_AdjustmentOut_Item" (
    "Id" BIGINT NOT NULL,
    "DetId" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "ItemCode" NVARCHAR(50),
    "ItemName" NVARCHAR(200),
    "FreeText" NVARCHAR(1000),
    "WhsCode" NVARCHAR(50),

    "PillarsCode" NVARCHAR(10),
    "PillarsName" NVARCHAR(50),
    "ClassCode" NVARCHAR(10),
    "ClassName" NVARCHAR(50),
    "SubClass1Code" NVARCHAR(10),
    "SubClass1Name" NVARCHAR(50),
    "SubClass2Code" NVARCHAR(10),
    "SubClass2Name" NVARCHAR(50),
    "ProjectCode" NVARCHAR(50),
    "ProjectName" NVARCHAR(100),

    "QuantityScan" DECIMAL(21, 2),
    "QuantityPosted" DECIMAL(21, 2), 
    "LineStatus" NVARCHAR(50),
    "UomEntry" INT,
    "Uom" NVARCHAR(50),
    "CreatedDate" TIMESTAMP,
    "CreatedUser" INTEGER,
    "ModifiedDate" TIMESTAMP,
    "ModifiedUser" INTEGER
);

DROP TABLE "Tx_AdjustmentOut_Item_Tag";
CREATE COLUMN TABLE "Tx_AdjustmentOut_Item_Tag" (
    "Id" BIGINT,
    "DetId" BIGINT,
    "DetDetId" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    "ItemCode" NVARCHAR(50),
    "ItemName" NVARCHAR(200),
    "TagId" NVARCHAR(200),
    "Quantity" DECIMAL(21,6),
    "EventType" NVARCHAR(100),
    "Status" NVARCHAR(50),
    "PostResultNote" NVARCHAR(500),
    "CreatedDate" TIMESTAMP,
    "CreatedUser" INTEGER,
    "ModifiedDate" TIMESTAMP,
    "ModifiedUser" INTEGER
);

DROP TABLE "Tx_PurchaseOrder";
CREATE COLUMN TABLE "Tx_PurchaseOrder" (
    "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "TransType" NVARCHAR(50),
    "TransNo" NVARCHAR(50),
    "TransDate" TIMESTAMP,
    "VendorCode" NVARCHAR(50),
    "VendorName" VARCHAR(100),
    "Address" NVARCHAR(254),
    "DocEntry" BIGINT,
    "DocNum" NVARCHAR(50),
    "DocDate" TIMESTAMP,
    "RefNo" NVARCHAR(100),
    "ScanDeviceId" NVARCHAR(1000),
    "Status" NVARCHAR(50),
    "IsAfterPosted" CHAR(1),
    "Comments" NVARCHAR(254),
    "CancelReason" NVARCHAR(254),
    "CreatedDate" TIMESTAMP,
    "CreatedUser" INTEGER,
    "ModifiedDate" TIMESTAMP,
    "ModifiedUser" INTEGER,
    PRIMARY KEY ("Id")
);

DROP TABLE "Tx_PurchaseOrder_Item";
CREATE COLUMN TABLE "Tx_PurchaseOrder_Item" (
    "Id" BIGINT,
    "DetId" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    "DocEntry" BIGINT,
    "DocNum" NVARCHAR(50),
    "BaseLine" INTEGER,
    "LineNum" INTEGER,
    "ItemCode" NVARCHAR(50),
    "ItemName" NVARCHAR(200),
    "WhsCode" NVARCHAR(50),
    "Quantity" DECIMAL(21,2),    
    "QuantityOpen" DECIMAL(21,2),
    "QuantityScan" DECIMAL(21,2),
    "UnitPriceTc" DECIMAL(21,2),
    "UomEntry" INTEGER,
    "Uom" NVARCHAR(50),
    "LineStatus" NVARCHAR(50),
    "IdPDO" INTEGER,
    "CreatedDate" TIMESTAMP,
    "CreatedUser" INTEGER,
    "ModifiedDate" TIMESTAMP,
    "ModifiedUser" INTEGER
);

DROP TABLE "Tx_GoodsReceiptPO";
CREATE COLUMN TABLE "Tx_GoodsReceiptPO"(
    "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "TransType" NVARCHAR(50),
    "TransNo" NVARCHAR(50),
    "TransDate" TIMESTAMP,
    "VendorCode" NVARCHAR(50),
    "VendorName" VARCHAR(100),
    "Address" NVARCHAR(254),
    "DocEntry" BIGINT,
    "DocNum" NVARCHAR(50),
    "DocDate" TIMESTAMP,
    "RefNo" NVARCHAR(100),
    "Status" NVARCHAR(50),
    "ApprovalStatus" NVARCHAR(50),
    "BaseEntry" BIGINT,
    "BaseDocNum" NVARCHAR(100),
    "PostingDate" TIMESTAMP,
    "IsAfterPosted" CHAR(1),
    "Comments" NVARCHAR(254),
    "CancelReason" NVARCHAR(254),
    "CreatedDate" TIMESTAMP,
    "CreatedUser" INTEGER,
    "ModifiedDate" TIMESTAMP,
    "ModifiedUser" INTEGER
);

DROP TABLE "Tx_GoodsReceiptPO_Ref";
CREATE COLUMN TABLE "Tx_GoodsReceiptPO_Ref" (
    "Id" BIGINT,
    "DetId" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    "BaseId" NVARCHAR(50),
    "BaseNo" NVARCHAR(200),
    "ScanDeviceId" NVARCHAR(1000),
    "Comments" NVARCHAR(254),
    "Status" NVARCHAR(50),
    "BaseCreatedDate" TIMESTAMP,
    "BaseCreatedUser" INTEGER,
    "CreatedDate" TIMESTAMP,
    "CreatedUser" INTEGER,
    "ModifiedDate" TIMESTAMP,
    "ModifiedUser" INTEGER
);

DROP TABLE "Tx_GoodsReceiptPO_Item";
CREATE COLUMN TABLE "Tx_GoodsReceiptPO_Item" (
    "Id" BIGINT,
    "DetId" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    "ItemCode" NVARCHAR(50),
    "ItemName" NVARCHAR(200),
    "WhsCode" NVARCHAR(50),
    "QuantityOnHandSAP" DECIMAL(21,2),
    "Quantity" DECIMAL(21,2),
    "QuantityOpen" DECIMAL(21,2),
    "QuantityScan" DECIMAL(21,2),
    "QuantityValid" DECIMAL(21,6),
    "UnitPriceTc" DECIMAL(21,2),
    "UomEntry" INTEGER,
    "Uom" NVARCHAR(50),
    "DocEntry" BIGINT,
    "DocNum" NVARCHAR(50),
    "LineNum" INTEGER,
    "BaseEntry" BIGINT,
    "BaseLine" INTEGER,
    "LineStatus" NVARCHAR(50),

    "IdPDO" INTEGER,
    "GoodsReceiptDocEntry" INTEGER,
    
    "CreatedDate" TIMESTAMP,
    "CreatedUser" INTEGER,
    "ModifiedDate" TIMESTAMP,
    "ModifiedUser" INTEGER
);

DROP TABLE "Tx_GoodsReceiptPO_Item_Tag" ;
CREATE COLUMN TABLE "Tx_GoodsReceiptPO_Item_Tag"
(
    "Id" BIGINT,
    "DetId" BIGINT,
    "DetDetId" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "ItemCode" NVARCHAR(50),
    "ItemName" NVARCHAR(200),
    "TagId" NVARCHAR(200),
    "Quantity" DECIMAL(21,6),
    "EventType" NVARCHAR(100),
    "Status" NVARCHAR(50),
    "BaseId" BIGINT,
    "BaseDetId" BIGINT,
    "BaseDetDetId" BIGINT,
    "CreatedDate" TIMESTAMP,
    "CreatedUser" INTEGER,
    "ModifiedDate" TIMESTAMP,
    "ModifiedUser" INTEGER
);

DROP TABLE "Tx_Request_StockOpname" ;
CREATE COLUMN TABLE "Tx_Request_StockOpname" (
    "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "TransType" NVARCHAR(50),
    "TransNo" NVARCHAR(50),
    "WhsCode" NVARCHAR(50),
    "WhsName" NVARCHAR(100),
    
    "StartDate" TIMESTAMP,
    "EndDate" TIMESTAMP,
    "Description" NVARCHAR(100),
    "Status" NVARCHAR(50),
    "CancelReason" NVARCHAR(50),

    "IsApproval" CHAR(1),
    "ApprovalMessages" NVARCHAR(254),

    "CreatedDate" TIMESTAMP,
    "CreatedUser" INTEGER,
    "ModifiedDate" TIMESTAMP,
    "ModifiedUser" INTEGER
);

DROP TABLE "Tx_StockOpname";
CREATE COLUMN TABLE "Tx_StockOpname" (
    "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "TransType" NVARCHAR(50),
    "TransNo" NVARCHAR(50),
    "TransDate" TIMESTAMP,
    "RequestId" BIGINT,
    "RequestNo" NVARCHAR(50),
    "WhsCode" NVARCHAR(50),
    "ScanDeviceId" NVARCHAR(1000),    
    "Status" NVARCHAR(50),
    "Comments" NVARCHAR(254),
    "CancelReason" NVARCHAR(500),
    "CreatedDate" TIMESTAMP,
    "CreatedUser" INTEGER,
    "ModifiedDate" TIMESTAMP,
    "ModifiedUser" INTEGER
);

DROP TABLE "Tx_StockOpname_Item";
CREATE COLUMN TABLE "Tx_StockOpname_Item" (
    "Id" BIGINT,
    "DetId" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "ItemCode" NVARCHAR(50),
    "ItemName" NVARCHAR(200),
    "WhsCode" NVARCHAR(50),
    "Quantity" DECIMAL(21,2),
    "QuantityScan" DECIMAL(21,2),
    "UomEntry" INTEGER,
    "Uom" NVARCHAR(50),
    "CreatedDate" TIMESTAMP,
    "CreatedUser" INTEGER,
    "ModifiedDate" TIMESTAMP,
    "ModifiedUser" INTEGER
);

DROP TABLE "Tx_StockOpname_Item_Tag";
CREATE COLUMN TABLE "Tx_StockOpname_Item_Tag" (
    "Id" BIGINT,
    "DetId" BIGINT,
    "DetDetId" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "ItemCode" NVARCHAR(50),
    "ItemName" NVARCHAR(200),
    "TagId" NVARCHAR(200),
    "Quantity" DECIMAL(21,6),
    "EventType" NVARCHAR(100),
    "Status" NVARCHAR(50),
    "PostResultNote" NVARCHAR(500),
    "CreatedDate" TIMESTAMP,
    "CreatedUser" INTEGER,
    "ModifiedDate" TIMESTAMP,
    "ModifiedUser" INTEGER
);

DROP TABLE "Tx_StockSummaryOpname";
CREATE COLUMN TABLE "Tx_StockSummaryOpname"(
    "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "TransType" NVARCHAR(50),
    "TransNo" NVARCHAR(50),
    
    "DocEntry" INT,
    "DocNum" NVARCHAR(50),
    "TransDate" TIMESTAMP,
    "PostingDate" TIMESTAMP,
    "RequestId" BIGINT,
    "RequestNo" NVARCHAR(100),

    "WhsCode" NVARCHAR(50),
    "WhsName" VARCHAR(100),

    "PillarsCode" NVARCHAR(10),
    "PillarsName" NVARCHAR(50),
    "ClassCode" NVARCHAR(10),
    "ClassName" NVARCHAR(50),
    "SubClass1Code" NVARCHAR(10),
    "SubClass1Name" NVARCHAR(50),
    "SubClass2Code" NVARCHAR(10),
    "SubClass2Name" NVARCHAR(50),
    "ProjectCode" NVARCHAR(50),
    "ProjectName" NVARCHAR(100),

    "Status" NVARCHAR(50),
    "ApprovalStatus" NVARCHAR(50),
    "IsAfterPosted" CHAR(1),
    "Comments" NVARCHAR(254),
    "CancelReason" NVARCHAR(254),    

    "IsApproval" CHAR(1),
    "ApprovalMessages" NVARCHAR(254),

    "CreatedDate" TIMESTAMP,
    "CreatedUser" INTEGER,
    "ModifiedDate" TIMESTAMP,
    "ModifiedUser" INTEGER
);

DROP TABLE "Tx_StockSummaryOpname_Ref";
CREATE COLUMN TABLE "Tx_StockSummaryOpname_Ref" (
    "Id" BIGINT,
    "DetId" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    "BaseId" NVARCHAR(50),
    "BaseNo" NVARCHAR(200),
    "ScanDeviceId" NVARCHAR(1000),
    "Comments" NVARCHAR(254),
    "Status" NVARCHAR(50),
    "BaseCreatedDate" TIMESTAMP,
    "BaseCreatedUser" INTEGER,
    "CreatedDate" TIMESTAMP,
    "CreatedUser" INTEGER,
    "ModifiedDate" TIMESTAMP,
    "ModifiedUser" INTEGER
);

DROP TABLE "Tx_StockSummaryOpname_Item";
CREATE COLUMN TABLE "Tx_StockSummaryOpname_Item" (
    "Id" BIGINT,
    "DetId" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    "ItemCode" NVARCHAR(50),
    "ItemName" NVARCHAR(200),
    "WhsCode" NVARCHAR(50),

    "QuantityOnHandSAP" DECIMAL(21,2),
    "QuantityScan" DECIMAL(21,2),
    "QuantityValid" DECIMAL(21,2),	
    "QtyVariance" DECIMAL(21,2),	
    "UnitPriceTc" DECIMAL(21,2),
    "UomEntry" INTEGER,
    "Uom" NVARCHAR(50),
    "AcctCode" NVARCHAR(100),
    "AcctName" NVARCHAR(100),

    "PillarsCode" NVARCHAR(10),
    "PillarsName" NVARCHAR(50),
    "ClassCode" NVARCHAR(10),
    "ClassName" NVARCHAR(50),
    "SubClass1Code" NVARCHAR(10),
    "SubClass1Name" NVARCHAR(50),
    "SubClass2Code" NVARCHAR(10),
    "SubClass2Name" NVARCHAR(50),
    "ProjectCode" NVARCHAR(50),
    "ProjectName" NVARCHAR(100),

    "FreeText" NVARCHAR(254),
    "CreatedDate" TIMESTAMP,
    "CreatedUser" INTEGER,
    "ModifiedDate" TIMESTAMP,
    "ModifiedUser" INTEGER
);

DROP TABLE "Tx_StockSummaryOpname_Item_Tag" ;
CREATE COLUMN TABLE "Tx_StockSummaryOpname_Item_Tag"
(
    "Id" BIGINT,
    "DetId" BIGINT,
    "DetDetId" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "ItemCode" NVARCHAR(50),
    "ItemName" NVARCHAR(200),
    "TagId" NVARCHAR(200),
    "Quantity" DECIMAL(21,6),
    "EventType" NVARCHAR(100),
    "Status" NVARCHAR(50),
    "BaseId" BIGINT,
    "BaseDetId" BIGINT,
    "BaseDetDetId" BIGINT,
    "CreatedDate" TIMESTAMP,
    "CreatedUser" INTEGER,
    "ModifiedDate" TIMESTAMP,
    "ModifiedUser" INTEGER
);

ALTER TABLE "Tm_GeneralSetting"
ADD (
	"StockOpnameCoaCode" NVARCHAR(50),
	"StockOpnameCoaName" NVARCHAR(200)
)
;

DROP TABLE "Tx_TransferRequest";
CREATE TABLE "Tx_TransferRequest" (
    "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    "TransType" NVARCHAR(50),
    "TransNo" NVARCHAR(50),
    "TransDate" TIMESTAMP,
    "DocEntry" BIGINT,
    "DocNum" NVARCHAR(50),
    "DocDate" TIMESTAMP,
    "VendorCode" NVARCHAR(50),
    "VendorName" VARCHAR(100),
    "Address" NVARCHAR(254),
    "FromWhsCode" NVARCHAR(50),
    "FromWhsName" VARCHAR(100),
    "ToWhsCode" NVARCHAR(50),
    "ToWhsName" VARCHAR(100),
    "PriceList" INTEGER,
    "PriceListName" NVARCHAR(50),
    "Status" NVARCHAR(50),
    "ApprovalStatus" NVARCHAR(50),
    "IsAfterPosted" CHAR(1),
    "Comments" NVARCHAR(254),
    "JournalRemarks" NVARCHAR(254),
    "CancelReason" NVARCHAR(254),
    "IsApproval" CHAR(1),
    "ApprovalMessages" NVARCHAR(254),

    "CreatedDate" TIMESTAMP,
    "CreatedUser" INTEGER,
    "ModifiedDate" TIMESTAMP,
    "ModifiedUser" INTEGER
);

DROP TABLE "Tx_TransferRequest_Item";
CREATE TABLE "Tx_TransferRequest_Item" (
    "Id" BIGINT,
    "DetId" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "ItemCode" NVARCHAR(50),
    "ItemName" NVARCHAR(200),
    "FromWhsCode" NVARCHAR(50),
    "FromWhsName" VARCHAR(100),
    "ToWhsCode" NVARCHAR(50),
    "ToWhsName" VARCHAR(100),
    "Quantity" DECIMAL(21,2),
    "QuantityOpen" DECIMAL(21,2),
    "QuantityScan" DECIMAL(21,2),
    "LineStatus" NVARCHAR(50),
    "UomEntry" INTEGER,
    "Uom" NVARCHAR(50),
    "Comments" NVARCHAR(254),
    "FreeText" NVARCHAR(200),
    "CreatedDate" TIMESTAMP,
    "CreatedUser" INTEGER,
    "ModifiedDate" TIMESTAMP,
    "ModifiedUser" INTEGER
);


DROP TABLE "Tx_TransferSummaryIn";
CREATE COLUMN TABLE "Tx_TransferSummaryIn" (
    "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "TransType" NVARCHAR(50),
    "TransNo" NVARCHAR(50),
    "TransDate" TIMESTAMP,
    "PostingDate" TIMESTAMP,
    "DocEntry" BIGINT,
    "DocNum" NVARCHAR(50),
    "DocDate" TIMESTAMP,
    
    "BaseId" BIGINT,
    "BaseTransNo" NVARCHAR(50),
    "BaseType" NVARCHAR(50),
    
    "VendorCode" NVARCHAR(50),
    "VendorName" VARCHAR(100),
    "Address" NVARCHAR(254),
    
    "FromWhsCode" NVARCHAR(50),
    "FromWhsName" VARCHAR(100),
    "TransitWhsCode" NVARCHAR(50),
    "TransitWhsName" NVARCHAR(100),
    "ToWhsCode" NVARCHAR(50),
    "ToWhsName" VARCHAR(100),
    
    "PriceList" INTEGER,
    "PriceListName" NVARCHAR(50),
    "Status" NVARCHAR(50),
    "ApprovalStatus" NVARCHAR(50),
    "IsAfterPosted" CHAR(1),
    "Comments" NVARCHAR(254),
    "JournalRemarks" NVARCHAR(254),
    "CancelReason" NVARCHAR(254),
    "IsApproval" CHAR(1),
    "ApprovalMessages" NVARCHAR(254),

    "CreatedDate" TIMESTAMP,
    "CreatedUser" INTEGER,
    "ModifiedDate" TIMESTAMP,
    "ModifiedUser" INTEGER
);

DROP TABLE "Tx_TransferSummaryIn_Item";
CREATE TABLE "Tx_TransferSummaryIn_Item" (
    "Id" INT NOT NULL,
    "DetId" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "BaseId" BIGINT,
    "BaseDetId" INTEGER,
    "BaseType" NVARCHAR(50),
    "ItemCode" NVARCHAR(50),
    "ItemName" NVARCHAR(200),
    "FromWhsCode" NVARCHAR(50),
    "FromWhsName" VARCHAR(100),
    "ToWhsCode" NVARCHAR(50),
    "ToWhsName" VARCHAR(100),
    "Quantity" DECIMAL(21,2),
    "QuantityOpen" DECIMAL(21,2),
    "QuantityScan" DECIMAL(21,2),
    "QuantityValid" DECIMAL(21,2),
    "QuantityPosted" DECIMAL(21,2),
    "UomEntry" INTEGER,
    "Uom" NVARCHAR(50),
    "Comments" NVARCHAR(254),
    "CreatedDate" TIMESTAMP,
    "CreatedUser" INTEGER,
    "ModifiedDate" TIMESTAMP,
    "ModifiedUser" INTEGER,
    "TransitWhsCode" NVARCHAR(50),
    "TransitWhsName" NVARCHAR(100)
);

DROP TABLE "Tx_TransferSummaryIn_Item_tag";
CREATE TABLE "Tx_TransferSummaryIn_Item_tag" (
    "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "DetId" BIGINT,
    "DetDetId" BIGINT,
    "ItemCode" NVARCHAR(50),
    "ItemName" NVARCHAR(200),
    "TagId" NVARCHAR(200),
    "Quantity" DECIMAL(21,6),
    "EventType" NVARCHAR(100),
    "Status" NVARCHAR(50),
    "BaseId" BIGINT,
    "BaseDetId" BIGINT,
    "BaseDetDetId" BIGINT,
    "CreatedDate" TIMESTAMP,
    "CreatedUser" INTEGER,
    "ModifiedDate" TIMESTAMP,
    "ModifiedUser" INTEGER
);

DROP TABLE "Tx_TransferSummaryIn_Ref";
CREATE COLUMN TABLE "Tx_TransferSummaryIn_Ref" (
    "Id" BIGINT,
    "DetId" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    "BaseId" NVARCHAR(50),
    "BaseNo" NVARCHAR(200),
    "ScanDeviceId" NVARCHAR(1000),
    "Comments" NVARCHAR(254),
    "Status" NVARCHAR(50),

    "BaseCreatedDate" TIMESTAMP,
    "BaseCreatedUser" INTEGER,
    "CreatedDate" TIMESTAMP,
    "CreatedUser" INTEGER,
    "ModifiedDate" TIMESTAMP,
    "ModifiedUser" INTEGER
);

DROP TABLE "Tx_TransferSummaryOut";
CREATE COLUMN TABLE "Tx_TransferSummaryOut" (
    "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "TransType" NVARCHAR(50),
    "TransNo" NVARCHAR(50),
    "TransDate" TIMESTAMP,
    "PostingDate" TIMESTAMP,
    "DocEntry" BIGINT,
    "DocNum" NVARCHAR(50),
    "DocDate" TIMESTAMP,
    "RequestId" BIGINT,
    "RequestNo" NVARCHAR(50),
    "BaseType" NVARCHAR(50),
    "VendorCode" NVARCHAR(50),
    "VendorName" VARCHAR(100),
    "Address" NVARCHAR(254),
    "FromWhsCode" NVARCHAR(50),
    "FromWhsName" VARCHAR(100),
    "TransitWhsCode" NVARCHAR(50),
    "TransitWhsName" NVARCHAR(100),
    "ToWhsCode" NVARCHAR(50),
    "ToWhsName" VARCHAR(100),
    "PriceList" INTEGER,
    "PriceListName" NVARCHAR(50),
    "ScanDeviceId" NVARCHAR(1000),
    "Status" NVARCHAR(50),
    "ApprovalStatus" NVARCHAR(50),
    "IsAfterPosted" CHAR(1),
    "Comments" NVARCHAR(254),
    "JournalRemarks" NVARCHAR(254),
    "CancelReason" NVARCHAR(254),

    "IsApproval" CHAR(1),
    "ApprovalMessages" NVARCHAR(254),

    "CreatedDate" TIMESTAMP,
    "CreatedUser" INTEGER,
    "ModifiedDate" TIMESTAMP,
    "ModifiedUser" INTEGER
);

DROP TABLE "Tx_TransferSummaryOut_Item";
CREATE COLUMN TABLE "Tx_TransferSummaryOut_Item"
(
    "Id"               BIGINT,
    "DetId"            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    "RequestId"           BIGINT,
    "RequestDetId"        BIGINT,
    "BaseType"         NVARCHAR(50),
    "ItemCode"         NVARCHAR(50),
    "ItemName"         NVARCHAR(200),
    "FromWhsCode"      NVARCHAR(50),
    "FromWhsName"      VARCHAR(100),
    "TransitWhsCode"   NVARCHAR(50),
    "TransitWhsName"   NVARCHAR(100),
    "ToWhsCode"        NVARCHAR(50),
    "ToWhsName"        VARCHAR(100),
    "QuantityRequest"         DECIMAL(21,2),
    "QuantityScan"     DECIMAL(21,2),
    "QuantityValid"     DECIMAL(21,2),
    "QuantityPosted"     DECIMAL(21,2),
    "QuantityToReceipt" DECIMAL(21,2),
    "LineStatus" NVARCHAR(50),
    "UomEntry"         INTEGER,
    "Uom"              NVARCHAR(50),
    "Comments"         NVARCHAR(254),
    "CreatedDate"      TIMESTAMP,
    "CreatedUser"      INTEGER,
    "ModifiedDate"     TIMESTAMP,
    "ModifiedUser"     INTEGER

);

DROP TABLE "Tx_TransferSummaryOut_Item_Tag";
CREATE COLUMN TABLE "Tx_TransferSummaryOut_Item_Tag"
(
    "Id"            BIGINT,
    "DetId"         BIGINT,
    "DetDetId"      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    "ItemCode"      NVARCHAR(50),
    "ItemName"      NVARCHAR(200),
    "TagId"         NVARCHAR(200),
    "Quantity"      DECIMAL(21,6),
    "EventType"     NVARCHAR(100),
    "Status"        NVARCHAR(50),
    "BaseId"        BIGINT,
    "BaseDetId"     BIGINT,
    "BaseDetDetId"  BIGINT,
    "CreatedDate"   TIMESTAMP,
    "CreatedUser"   INTEGER,
    "ModifiedDate"  TIMESTAMP,
    "ModifiedUser"  INTEGER
);

DROP TABLE "Tx_TransferSummaryOut_Ref";
CREATE COLUMN TABLE "Tx_TransferSummaryOut_Ref" (
    "Id" BIGINT,
    "DetId" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    "BaseId" NVARCHAR(50),
    "BaseNo" NVARCHAR(200),
    "ScanDeviceId" NVARCHAR(1000),
    "Comments" NVARCHAR(254),
    "Status" NVARCHAR(50),

    "BaseCreatedDate" TIMESTAMP,
    "BaseCreatedUser" INTEGER,
    "CreatedDate" TIMESTAMP,
    "CreatedUser" INTEGER,
    "ModifiedDate" TIMESTAMP,
    "ModifiedUser" INTEGER
);

DROP TABLE "Tm_Item_Warehouse_Tag_Replace";
CREATE COLUMN TABLE "Tm_Item_Warehouse_Tag_Replace" (
    "TagId" NVARCHAR(200) NOT NULL,
    "ItemCode" NVARCHAR(50) NOT NULL,
    "ItemName" NVARCHAR(200),
    "WhsCode" NVARCHAR(50),
    "WhsName" NVARCHAR(200),
    "CreatedDate" TIMESTAMP,
    "CreatedUser" INTEGER,
    "ModifiedDate" TIMESTAMP,
    "ModifiedUser" INTEGER,
    PRIMARY KEY ("TagId", "ItemCode")
);

DROP TABLE "Tm_Item_Warehouse_Tag_Log";
CREATE COLUMN TABLE "Tm_Item_Warehouse_Tag_Log"
(
    "LogId" BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
    "BaseType" NVARCHAR(50) ,
    "ItemCode" NVARCHAR(50) NOT NULL,
    "ItemName" NVARCHAR(200),
    "WhsCode" NVARCHAR(50),
    "WhsName" NVARCHAR(200),
    "OldTagId" NVARCHAR(200),
    "TagId" NVARCHAR(200),
    "Status"  NVARCHAR(200),
    "Event" NVARCHAR(100),
    "ActionNote" NVARCHAR(500),
    "CreatedDate" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "CreatedUser" INTEGER,
    PRIMARY KEY ("LogId")
);

DROP TABLE "Tx_DeactiveTag_Log";
CREATE COLUMN TABLE "Tx_DeactiveTag_Log"
(
    "LogId" BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
    "TagId" NVARCHAR(200),    
    "ItemCode" NVARCHAR(50) NOT NULL,
    "ItemName" NVARCHAR(200),
    "WhsCode" NVARCHAR(50),
    "WhsName" NVARCHAR(200),
    "Message" NVARCHAR(5000),
    "CreatedDate" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "CreatedUser" INTEGER,
    PRIMARY KEY ("LogId")
);

DROP TABLE "Tx_DeactiveTag" ;
CREATE COLUMN TABLE "Tx_DeactiveTag" (
    "Id" BIGINT  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    "TransType" NVARCHAR(50),
    "TransNo" NVARCHAR(50),
    "ScanDeviceId" NVARCHAR(1000),
    "TransDate" TIMESTAMP,
    "PostingDate" TIMESTAMP,
    "Status" NVARCHAR(50),
    "ApprovalStatus" NVARCHAR(50),
    "Comments" NVARCHAR(200),
    "CancelReason" NVARCHAR(500),
    "IsApproval" CHAR(1),
    "ApprovalMessages" NVARCHAR(254),    
    "CreatedDate" TIMESTAMP,
    "CreatedUser" INTEGER,
    "ModifiedDate" TIMESTAMP,
    "ModifiedUser" INTEGER
);

DROP TABLE "Tx_DeactiveTag_Item";
CREATE COLUMN TABLE "Tx_DeactiveTag_Item" (
    "Id" BIGINT NOT NULL,
    "DetId" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    "TagId" NVARCHAR(200),
    "ItemCode" NVARCHAR(50),
    "ItemName" NVARCHAR(200),
    "FreeText" NVARCHAR(1000),
    "WhsCode" NVARCHAR(50),
    "WhsName" NVARCHAR(200),    
    "CreatedDate" TIMESTAMP,
    "CreatedUser" INTEGER,
    "ModifiedDate" TIMESTAMP,
    "ModifiedUser" INTEGER
);

DROP TABLE "Tx_DeactiveTag_Approval";
CREATE COLUMN TABLE "Tx_DeactiveTag_Approval"
(
    "Id" INTEGER CS_INT,
    "DetId" INTEGER CS_INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "StageId" INTEGER CS_INT,
    "UserId" INTEGER CS_INT,
    "Step" INTEGER CS_INT,
    "Status" NVARCHAR(50),
    "Comments" NVARCHAR(1000),
    "ActionDate" SECONDDATE CS_SECONDDATE,
    "CreatedDate" SECONDDATE CS_SECONDDATE,
    "CreatedUser" INTEGER CS_INT,
    "ModifiedDate" SECONDDATE CS_SECONDDATE,
    "ModifiedUser" INTEGER CS_INT,
    PRIMARY KEY ("DetId")
)
;

DROP TABLE "Tm_Layout";
CREATE COLUMN TABLE "Tm_Layout"
(
    "Id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "TransType" NVARCHAR(50),
    "LayoutFormCode" NVARCHAR(50),
    "LayoutName" NVARCHAR(50),
    "Description" NVARCHAR(1000),
    "Uid" NVARCHAR(50),
    "Data" BLOB,
    "OutputType" NVARCHAR(50),
    "IsActive" CHAR(1),
    "CreatedDate" TIMESTAMP,
    "CreatedUser" INTEGER,
    "ModifiedDate" TIMESTAMP,
    "ModifiedUser" INTEGER,
    PRIMARY KEY ("Id")
);

DROP TABLE "Tm_Layout_Role";
CREATE COLUMN TABLE "Tm_Layout_Role"
(
    "Id" INTEGER,
    "DetId" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "RoleId" INTEGER,
    "IsTick" CHAR(1),
    "CreatedDate" TIMESTAMP,
    "CreatedUser" INTEGER,
    "ModifiedDate" TIMESTAMP,
    "ModifiedUser" INTEGER,
    PRIMARY KEY ("DetId")
);

DROP TABLE "Tm_Layout_User";
CREATE COLUMN TABLE "Tm_Layout_User"
(
    "Id" INTEGER,
    "DetId" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "UserId" INTEGER,
    "IsTick" CHAR(1),
    "CreatedDate" TIMESTAMP,
    "CreatedUser" INTEGER,
    "ModifiedDate" TIMESTAMP,
    "ModifiedUser" INTEGER,
    PRIMARY KEY ("DetId")
);

DROP TABLE "Tp_UserAlert";
CREATE TABLE "Tp_UserAlert"
(
    "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
    "UserId" INT,
    "BaseType" NVARCHAR(50),
    "BaseId" BIGINT,
    "BaseTransNo" NVARCHAR(100),
    "Action" NVARCHAR(100),
    "NotificationMessage" NVARCHAR(500),
    "SenderId" INT,
    "IsRead" CHAR(1),
    "LastShowTime" TIMESTAMP
);


DROP TABLE "Tm_Approval";
CREATE COLUMN TABLE "Tm_Approval"
(
    "Id" INTEGER CS_INT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
    "TransType"     NVARCHAR(50),
    "FormCode"      NVARCHAR(50),
    "ApprovalName"  NVARCHAR(50),
    "IsActive"      CHAR(1) CS_FIXEDSTRING,
    "CreatedDate"   LONGDATE CS_LONGDATE,
    "CreatedUser"   INTEGER CS_INT,
    "ModifiedDate"  LONGDATE CS_LONGDATE,
    "ModifiedUser"  INTEGER CS_INT,
    PRIMARY KEY ("Id")
)
UNLOAD PRIORITY 5
AUTO MERGE;

DROP TABLE "Tm_Approval_Role";
CREATE COLUMN TABLE "Tm_Approval_Role"
(
    "Id" INTEGER CS_INT,
    "DetId" INTEGER CS_INT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
    "RoleId" INTEGER CS_INT,
    "IsTick" CHAR(1) CS_FIXEDSTRING,
    "CreatedDate" LONGDATE CS_LONGDATE,
    "CreatedUser" INTEGER CS_INT,
    "ModifiedDate" LONGDATE CS_LONGDATE,
    "ModifiedUser" INTEGER CS_INT,
    PRIMARY KEY ("DetId")
)
UNLOAD PRIORITY 5
AUTO MERGE;

DROP TABLE "Tm_Approval_User";
CREATE COLUMN TABLE "Tm_Approval_User"
(
    "Id" INTEGER CS_INT,
    "DetId" INTEGER CS_INT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
    "UserId" INTEGER CS_INT,
    "IsTick" CHAR(1) CS_FIXEDSTRING,
    "CreatedDate" LONGDATE CS_LONGDATE,
    "CreatedUser" INTEGER CS_INT,
    "ModifiedDate" LONGDATE CS_LONGDATE,
    "ModifiedUser" INTEGER CS_INT,
    PRIMARY KEY ("DetId")
)
UNLOAD PRIORITY 5
AUTO MERGE;

DROP TABLE "Tm_ApprovalStage"
CREATE COLUMN TABLE "Tm_ApprovalStage"
(
    "Id" INTEGER CS_INT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
    "TransType" NVARCHAR(50),
    "StageName" VARCHAR(50),
    "Description" NVARCHAR(100),
    "MinApprove" INTEGER CS_INT,
    "MinReject" INTEGER CS_INT,
    "CreatedDate" LONGDATE CS_LONGDATE,
    "CreatedUser" INTEGER CS_INT,
    "ModifiedDate" LONGDATE CS_LONGDATE,
    "ModifiedUser" INTEGER CS_INT,
    PRIMARY KEY ("Id")
)
UNLOAD PRIORITY 5
AUTO MERGE;

DROP TABLE "Tm_ApprovalStage_Role";
CREATE COLUMN TABLE "Tm_ApprovalStage_Role"
(
    "Id" INTEGER CS_INT,
    "DetId" INTEGER CS_INT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
    "RoleId" INTEGER CS_INT,
    "IsTick" CHAR(1) CS_FIXEDSTRING,
    "CreatedDate" LONGDATE CS_LONGDATE,
    "CreatedUser" INTEGER CS_INT,
    "ModifiedDate" LONGDATE CS_LONGDATE,
    "ModifiedUser" INTEGER CS_INT,
    PRIMARY KEY ("DetId")
)
UNLOAD PRIORITY 5
AUTO MERGE;

DROP TABLE "Tm_ApprovalStage_User";
CREATE COLUMN TABLE "Tm_ApprovalStage_User"
(
    "Id" INTEGER CS_INT,
    "DetId" INTEGER CS_INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "UserId" INTEGER CS_INT,
    "IsTick" CHAR(1) CS_FIXEDSTRING,
    "CreatedDate" SECONDDATE CS_SECONDDATE,
    "CreatedUser" INTEGER CS_INT,
    "ModifiedDate" SECONDDATE CS_SECONDDATE,
    "ModifiedUser" INTEGER CS_INT,
    PRIMARY KEY ("DetId")
)
UNLOAD PRIORITY 5
AUTO MERGE;

DROP TABLE "Tm_ApprovalTemplate";
CREATE COLUMN TABLE "Tm_ApprovalTemplate"
(
    "Id" INTEGER CS_INT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
    "TransType" NVARCHAR(50),
    "TemplateName" VARCHAR(50),
    "ObjectCode" VARCHAR(50),
    "IsActive" CHAR(1) CS_FIXEDSTRING,
    "Sql" CLOB MEMORY THRESHOLD 1000,
    "CreatedDate" LONGDATE CS_LONGDATE,
    "CreatedUser" INTEGER CS_INT,
    "ModifiedDate" LONGDATE CS_LONGDATE,
    "ModifiedUser" INTEGER CS_INT,
    PRIMARY KEY ("Id")
)
UNLOAD PRIORITY 5
AUTO MERGE;

DROP TABLE "Tm_ApprovalTemplate_Position";
CREATE COLUMN TABLE "Tm_ApprovalTemplate_Position"
(
    "Id" INTEGER CS_INT,
    "DetId" INTEGER CS_INT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
    "Position" NVARCHAR(50),
    "IsTick" CHAR(1) CS_FIXEDSTRING,
    "CreatedDate" LONGDATE CS_LONGDATE,
    "CreatedUser" INTEGER CS_INT,
    "ModifiedDate" LONGDATE CS_LONGDATE,
    "ModifiedUser" INTEGER CS_INT,
    PRIMARY KEY ("DetId")
)
UNLOAD PRIORITY 5
AUTO MERGE;

DROP TABLE "Tm_ApprovalTemplate_Role";
CREATE COLUMN TABLE "Tm_ApprovalTemplate_Role"
(
    "Id" INTEGER CS_INT,
    "DetId" INTEGER CS_INT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
    "RoleId" INTEGER CS_INT,
    "IsTick" CHAR(1) CS_FIXEDSTRING,
    "CreatedDate" LONGDATE CS_LONGDATE,
    "CreatedUser" INTEGER CS_INT,
    "ModifiedDate" LONGDATE CS_LONGDATE,
    "ModifiedUser" INTEGER CS_INT,
    PRIMARY KEY ("DetId")
)
UNLOAD PRIORITY 5
AUTO MERGE;

DROP TABLE "Tm_ApprovalTemplate_Stage";
CREATE COLUMN TABLE "Tm_ApprovalTemplate_Stage"
(
    "Id" INTEGER CS_INT,
    "DetId" INTEGER CS_INT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
    "StageId" INTEGER CS_INT,
    "Step" INTEGER CS_INT,
    "SortCode" NVARCHAR(50),
    "CreatedDate" LONGDATE CS_LONGDATE,
    "CreatedUser" INTEGER CS_INT,
    "ModifiedDate" LONGDATE CS_LONGDATE,
    "ModifiedUser" INTEGER CS_INT,
    PRIMARY KEY ("DetId")
)
UNLOAD PRIORITY 5
AUTO MERGE;

DROP TABLE "Tm_ApprovalTemplate_User";
CREATE COLUMN TABLE "Tm_ApprovalTemplate_User"
(
    "Id" INTEGER CS_INT,
    "DetId" BIGINT CS_FIXED GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
    "UserId" INTEGER CS_INT,
    "IsTick" NVARCHAR(1),
    "CreatedDate" LONGDATE CS_LONGDATE,
    "CreatedUser" INTEGER CS_INT,
    "ModifiedDate" LONGDATE CS_LONGDATE,
    "ModifiedUser" INTEGER CS_INT,
    PRIMARY KEY ("DetId")
)
UNLOAD PRIORITY 5
AUTO MERGE;

DROP TABLE "Tp_Approval";
CREATE COLUMN TABLE "Tp_Approval"
(
    "Id" INTEGER CS_INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "TransType" NVARCHAR(50),
    "TemplateId" INTEGER CS_INT,
    "CurrentStep" INTEGER CS_INT,
    "ObjectId" NVARCHAR(255),
    "ObjectCode" NVARCHAR(50),
    "Status" NVARCHAR(50),
    "FlagNo" NVARCHAR(50),
    "CreatedDate" SECONDDATE CS_SECONDDATE,
    "CreatedUser" INTEGER CS_INT,
    "ModifiedDate" SECONDDATE CS_SECONDDATE,
    "ModifiedUser" INTEGER CS_INT,
    PRIMARY KEY ("Id")
)
UNLOAD PRIORITY 5
AUTO MERGE;

DROP TABLE "Tm_Item";
CREATE COLUMN TABLE "Tm_Item"
(
    "ItemCode" NVARCHAR(50),
    "ItemName" NVARCHAR(200),
    "OnHand" DECIMAL(21,6) CS_FIXED,
    "IsCommitted" DECIMAL(21,2) CS_FIXED,
    "OnOrder" DECIMAL(21,2) CS_FIXED,
    "UomEntry" INTEGER CS_INT,
    "Uom" NVARCHAR(50),
    "StockOpnameCoaCode" NVARCHAR(50),
    "StockOpnameCoaName" NVARCHAR(200),   
    "CreatedDate" LONGDATE CS_LONGDATE,
    "CreatedUser" INTEGER CS_INT,
    "ModifiedDate" LONGDATE CS_LONGDATE,
    "ModifiedUser" INTEGER CS_INT,
 
    PRIMARY KEY ("ItemCode")
)
UNLOAD PRIORITY 5
AUTO MERGE;

DROP TABLE "Tm_Item_Warehouse";
CREATE COLUMN TABLE "Tm_Item_Warehouse"
(
    "ItemCode" NVARCHAR(50) NOT NULL,
    "ItemName" NVARCHAR(200),
    "WhsCode" NVARCHAR(50),
    "WhsName" NVARCHAR(200),
    "OnHand" DECIMAL(21,6) CS_FIXED,
    "IsCommitted" DECIMAL(21,2) CS_FIXED,
    "OnOrder" DECIMAL(21,2) CS_FIXED,
    "UomEntry" INTEGER CS_INT,
    "Uom" NVARCHAR(50),
    "CreatedDate" LONGDATE CS_LONGDATE,
    "CreatedUser" INTEGER CS_INT,
    "ModifiedDate" LONGDATE CS_LONGDATE,
    "ModifiedUser" INTEGER CS_INT,
    PRIMARY KEY ("ItemCode", "WhsCode")
)
UNLOAD PRIORITY 5
AUTO MERGE;

DROP TABLE "Tm_Item_Warehouse_Tag";
CREATE COLUMN TABLE "Tm_Item_Warehouse_Tag"
(
    "TagId" NVARCHAR(200),
    "ItemCode" NVARCHAR(50),
    "ItemName" NVARCHAR(200),
    "WhsCode" NVARCHAR(50),
    "WhsName" NVARCHAR(200),
    "Status" NVARCHAR(50),
    "CreatedDate" LONGDATE CS_LONGDATE,
    "CreatedUser" INTEGER CS_INT,
    "ModifiedDate" LONGDATE CS_LONGDATE,
    "ModifiedUser" INTEGER CS_INT,
    "OnHand" DECIMAL(21,6) CS_FIXED,
    "IsCommitted" DECIMAL(21,2) CS_FIXED,
    "OnOrder" DECIMAL(21,2) CS_FIXED,
    "DeactiveRemarks" NVARCHAR(100),
    PRIMARY KEY ("TagId", "ItemCode")
)
UNLOAD PRIORITY 5
AUTO MERGE;

DROP TABLE "Tx_TransferIn";
CREATE COLUMN TABLE "Tx_TransferIn"
(
    "Id" BIGINT CS_FIXED GENERATED BY DEFAULT AS IDENTITY,
    "TransType" NVARCHAR(50),
    "TransNo" NVARCHAR(50),
    "TransDate" LONGDATE CS_LONGDATE,
    "DocEntry" BIGINT CS_FIXED,
    "DocNum" NVARCHAR(50),
    "DocDate" LONGDATE CS_LONGDATE,
    "BaseEntry" BIGINT CS_FIXED,
    "BaseDocNum" NVARCHAR(50),
    "BaseType" NVARCHAR(50),
    "VendorCode" NVARCHAR(50),
    "VendorName" VARCHAR(100),
    "Address" NVARCHAR(254),
    "FromWhsCode" NVARCHAR(50),
    "FromWhsName" VARCHAR(100),
    "ToWhsCode" NVARCHAR(50),
    "ToWhsName" VARCHAR(100),
    "ScanDeviceId" NVARCHAR(1000),
    "Status" NVARCHAR(50),
    "IsAfterPosted" CHAR(1) CS_FIXEDSTRING,
    "Comments" NVARCHAR(254),
    "JournalRemarks" NVARCHAR(254),
    "CancelReason" NVARCHAR(254),
    "ModifiedUser" INTEGER CS_INT,
    "PriceList" NVARCHAR(100),
    "PriceListName" NVARCHAR(100),
    "CreatedDate" LONGDATE CS_LONGDATE,
    "CreatedUser" INTEGER CS_INT,
    "ModifiedDate" LONGDATE CS_LONGDATE,
    PRIMARY KEY ("Id")
)
UNLOAD PRIORITY 5
AUTO MERGE;

DROP TABLE "Tx_TransferIn_Item";
CREATE COLUMN TABLE "Tx_TransferIn_Item"
(
    "Id" BIGINT CS_FIXED,
    "DetId" BIGINT CS_FIXED GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "BaseEntry" BIGINT CS_FIXED,
    "BaseLine" INTEGER CS_INT,
    "BaseType" NVARCHAR(50),
    "ItemCode" NVARCHAR(50),
    "ItemName" NVARCHAR(200),
    "FromWhsCode" NVARCHAR(50),
    "FromWhsName" VARCHAR(100),
    "ToWhsCode" NVARCHAR(50),
    "ToWhsName" VARCHAR(100),
    "Quantity" DECIMAL(21,2) CS_FIXED,
    "QuantityOpen" DECIMAL(21,2) CS_FIXED,
    "QuantityScan" DECIMAL(21,2) CS_FIXED,
    "UomEntry" INTEGER CS_INT,
    "Uom" NVARCHAR(50),
    "Comments" NVARCHAR(254),
    "CreatedDate" LONGDATE CS_LONGDATE,
    "CreatedUser" INTEGER CS_INT,
    "ModifiedDate" LONGDATE CS_LONGDATE,
    "ModifiedUser" INTEGER CS_INT,
    PRIMARY KEY ("DetId")
)
UNLOAD PRIORITY 5
AUTO MERGE;

DROP TABLE "Tx_TransferIn_Item_Tag";
CREATE COLUMN TABLE "Tx_TransferIn_Item_Tag"
(
    "Id" BIGINT CS_FIXED,
    "DetId" BIGINT CS_FIXED,
    "DetDetId" BIGINT CS_FIXED GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "ItemCode" NVARCHAR(50),
    "ItemName" NVARCHAR(200),
    "TagId" NVARCHAR(200),
    "Quantity" DECIMAL(21,6) CS_FIXED,
    "EventType" NVARCHAR(100),
    "Status" NVARCHAR(50),
    "BaseId" BIGINT CS_FIXED,
    "BaseDetId" BIGINT CS_FIXED,
    "CreatedDate" LONGDATE CS_LONGDATE,
    "CreatedUser" INTEGER CS_INT,
    "ModifiedDate" LONGDATE CS_LONGDATE,
    "ModifiedUser" INTEGER CS_INT,
    PRIMARY KEY ("DetDetId")
)
UNLOAD PRIORITY 5
AUTO MERGE;


DROP TABLE "Tx_TransferOut";
CREATE COLUMN TABLE "Tx_TransferOut"
(
    "Id" BIGINT CS_FIXED GENERATED BY DEFAULT AS IDENTITY,
    "TransType" NVARCHAR(50),
    "TransNo" NVARCHAR(50),
    "TransDate" LONGDATE CS_LONGDATE,
    "DocEntry" BIGINT CS_FIXED,
    "DocNum" NVARCHAR(50),
    "DocDate" LONGDATE CS_LONGDATE,
    "BaseEntry" BIGINT CS_FIXED,
    "BaseDocNum" NVARCHAR(50),
    "VendorCode" NVARCHAR(50),
    "VendorName" VARCHAR(100),
    "Address" NVARCHAR(254),
    "FromWhsCode" NVARCHAR(50),
    "FromWhsName" VARCHAR(100),
    "ToWhsCode" NVARCHAR(50),
    "ToWhsName" VARCHAR(100),
    "PriceList" INTEGER CS_INT,
    "PriceListName" NVARCHAR(50),
    "ScanDeviceId" NVARCHAR(1000),
    "Status" NVARCHAR(50),
    "IsAfterPosted" CHAR(1) CS_FIXEDSTRING,
    "Comments" NVARCHAR(254),
    "JournalRemarks" NVARCHAR(254),
    "CancelReason" NVARCHAR(254),
    "CreatedDate" LONGDATE CS_LONGDATE,
    "CreatedUser" INTEGER CS_INT,
    "ModifiedDate" LONGDATE CS_LONGDATE,
    "ModifiedUser" INTEGER CS_INT,
    PRIMARY KEY ("Id")
)
UNLOAD PRIORITY 5
AUTO MERGE;

DROP TABLE "Tx_TransferOut_Item";
CREATE COLUMN TABLE "Tx_TransferOut_Item"
(
    "Id" BIGINT CS_FIXED,
    "DetId" BIGINT CS_FIXED GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "BaseEntry" BIGINT CS_FIXED,
    "BaseLine" INTEGER CS_INT,
    "BaseType" NVARCHAR(50),
    "ItemCode" NVARCHAR(50),
    "ItemName" NVARCHAR(200),
    "FromWhsCode" NVARCHAR(50),
    "FromWhsName" VARCHAR(100),
    "ToWhsCode" NVARCHAR(50),
    "ToWhsName" VARCHAR(100),
    "Quantity" DECIMAL(21,2) CS_FIXED,
    "QuantityOpen" DECIMAL(21,2) CS_FIXED,
    "QuantityScan" DECIMAL(21,2) CS_FIXED,
    "UomEntry" INTEGER CS_INT,
    "Uom" NVARCHAR(50),
    "Comments" NVARCHAR(254),
    "CreatedDate" LONGDATE CS_LONGDATE,
    "CreatedUser" INTEGER CS_INT,
    "ModifiedDate" LONGDATE CS_LONGDATE,
    "ModifiedUser" INTEGER CS_INT,
    PRIMARY KEY ("DetId")
)
UNLOAD PRIORITY 5
AUTO MERGE;

DROP TABLE "Tx_TransferOut_Item_Tag";
CREATE COLUMN TABLE "Tx_TransferOut_Item_Tag"
(
    "Id" BIGINT CS_FIXED,
    "DetId" BIGINT CS_FIXED,
    "DetDetId" BIGINT CS_FIXED GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "ItemCode" NVARCHAR(50),
    "ItemName" NVARCHAR(200),
    "TagId" NVARCHAR(200),
    "Quantity" DECIMAL(21,6) CS_FIXED,
    "EventType" NVARCHAR(100),
    "Status" NVARCHAR(50),
    "BaseId" BIGINT CS_FIXED,
    "BaseDetId" BIGINT CS_FIXED,
    "CreatedDate" LONGDATE CS_LONGDATE,
    "CreatedUser" INTEGER CS_INT,
    "ModifiedDate" LONGDATE CS_LONGDATE,
    "ModifiedUser" INTEGER CS_INT,
    PRIMARY KEY ("DetDetId")
)
UNLOAD PRIORITY 5
AUTO MERGE;

DROP TABLE "Tx_TransferRequest";
CREATE COLUMN TABLE "Tx_TransferRequest"
(
    "Id" BIGINT CS_FIXED GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "TransType" NVARCHAR(50),
    "TransNo" NVARCHAR(50),
    "TransDate" LONGDATE CS_LONGDATE,
    "DocEntry" BIGINT CS_FIXED,
    "DocNum" NVARCHAR(50),
    "DocDate" LONGDATE CS_LONGDATE,
    "VendorCode" NVARCHAR(50),
    "VendorName" VARCHAR(100),
    "Address" NVARCHAR(254),
    "FromWhsCode" NVARCHAR(50),
    "FromWhsName" VARCHAR(100),
    "ToWhsCode" NVARCHAR(50),
    "ToWhsName" VARCHAR(100),
    "PriceList" INTEGER CS_INT,
    "PriceListName" NVARCHAR(50),
    "Status" NVARCHAR(50),
    "ApprovalStatus" NVARCHAR(50),
    "IsAfterPosted" CHAR(1) CS_FIXEDSTRING,
    "Comments" NVARCHAR(254),
    "JournalRemarks" NVARCHAR(254),
    "CancelReason" NVARCHAR(254),
    "IsApproval" CHAR(1) CS_FIXEDSTRING,
    "ApprovalMessage" NVARCHAR(254),

    "CreatedDate" LONGDATE CS_LONGDATE,
    "CreatedUser" INTEGER CS_INT,
    "ModifiedDate" LONGDATE CS_LONGDATE,
    "ModifiedUser" INTEGER CS_INT,
    PRIMARY KEY ("Id")
)
UNLOAD PRIORITY 5
AUTO MERGE;

DROP TABLE "Tx_TransferRequest_Approval";
CREATE COLUMN TABLE "Tx_TransferRequest_Approval"
(
    "Id" INTEGER CS_INT,
    "DetId" INTEGER CS_INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "StageId" INTEGER CS_INT,
    "UserId" INTEGER CS_INT,
    "Step" INTEGER CS_INT,
    "Status" NVARCHAR(50),
    "Comments" NVARCHAR(1000),
    "ActionDate" SECONDDATE CS_SECONDDATE,
    "CreatedDate" SECONDDATE CS_SECONDDATE,
    "CreatedUser" INTEGER CS_INT,
    "ModifiedDate" SECONDDATE CS_SECONDDATE,
    "ModifiedUser" INTEGER CS_INT,
    PRIMARY KEY ("DetId")
)
UNLOAD PRIORITY 5
AUTO MERGE;

DROP TABLE "Tx_TransferRequest_Item";
CREATE COLUMN TABLE "Tx_TransferRequest_Item"
(
    "Id" BIGINT CS_FIXED,
    "DetId" BIGINT CS_FIXED GENERATED BY DEFAULT AS IDENTITY,
    "ItemCode" NVARCHAR(50),
    "ItemName" NVARCHAR(200),
    "FromWhsCode" NVARCHAR(50),
    "FromWhsName" VARCHAR(100),
    "ToWhsCode" NVARCHAR(50),
    "ToWhsName" VARCHAR(100),
    "Quantity" DECIMAL(21,2) CS_FIXED,
    "QuantityOpen" DECIMAL(21,2) CS_FIXED,
    "QuantityScan" DECIMAL(21,2) CS_FIXED,
    "LineStatus" NVARCHAR(50),
    "UomEntry" INTEGER CS_INT,
    "Uom" NVARCHAR(50),
    "Comments" NVARCHAR(254),
    "FreeText" NVARCHAR(200),
    "CreatedDate" LONGDATE CS_LONGDATE,
    "CreatedUser" INTEGER CS_INT,
    "ModifiedDate" LONGDATE CS_LONGDATE,
    "ModifiedUser" INTEGER CS_INT,
    PRIMARY KEY ("DetId")
)
UNLOAD PRIORITY 5
AUTO MERGE;

DROP TABLE "Tx_TransferSummaryIn";
CREATE COLUMN TABLE "Tx_TransferSummaryIn"
(
    "Id" BIGINT CS_FIXED GENERATED BY DEFAULT AS IDENTITY,
    "TransType" NVARCHAR(50),
    "TransNo" NVARCHAR(50),
    "TransDate" LONGDATE CS_LONGDATE,
    "PostingDate" LONGDATE CS_LONGDATE,
    "DocEntry" BIGINT CS_FIXED,
    "DocNum" NVARCHAR(50),
    "DocDate" LONGDATE CS_LONGDATE,
    "BaseId" BIGINT CS_FIXED,
    "BaseTransNo" NVARCHAR(50),
    "BaseType" NVARCHAR(50),
    "VendorCode" NVARCHAR(50),
    "VendorName" VARCHAR(100),
    "Address" NVARCHAR(254),
    "FromWhsCode" NVARCHAR(50),
    "FromWhsName" VARCHAR(100),
    "TransitWhsCode" NVARCHAR(50),
    "TransitWhsName" VARCHAR(100),
    "ToWhsCode" NVARCHAR(50),
    "ToWhsName" VARCHAR(100),
    "PriceList" INTEGER CS_INT,
    "PriceListName" NVARCHAR(50),
    "Status" NVARCHAR(50),
    "ApprovalStatus" NVARCHAR(50),
    "IsAfterPosted" CHAR(1) CS_FIXEDSTRING,
    "Comments" NVARCHAR(254),
    "JournalRemarks" NVARCHAR(254),
    "CancelReason" NVARCHAR(254),
    "IsApproval" CHAR(1) CS_FIXEDSTRING,
    "ApprovalMessage" NVARCHAR(254),
    "CreatedDate" LONGDATE CS_LONGDATE,
    "CreatedUser" INTEGER CS_INT,
    "ModifiedDate" LONGDATE CS_LONGDATE,
    "ModifiedUser" INTEGER CS_INT,
    PRIMARY KEY ("Id")
)
UNLOAD PRIORITY 5
AUTO MERGE;

DROP TABLE "Tx_TransferSummaryIn_Approval";
CREATE COLUMN TABLE "Tx_TransferSummaryIn_Approval"
(
    "Id" INTEGER CS_INT,
    "DetId" INTEGER CS_INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "StageId" INTEGER CS_INT,
    "UserId" INTEGER CS_INT,
    "Step" INTEGER CS_INT,
    "Status" NVARCHAR(50),
    "Comments" NVARCHAR(1000),
    "ActionDate" SECONDDATE CS_SECONDDATE,
    "CreatedDate" SECONDDATE CS_SECONDDATE,
    "CreatedUser" INTEGER CS_INT,
    "ModifiedDate" SECONDDATE CS_SECONDDATE,
    "ModifiedUser" INTEGER CS_INT,
    PRIMARY KEY ("DetId")
)
UNLOAD PRIORITY 5
AUTO MERGE;

DROP TABLE "Tx_TransferSummaryIn_Item";
CREATE COLUMN TABLE "Tx_TransferSummaryIn_Item"
(
    "Id" INTEGER CS_INT NOT NULL,
    "DetId" BIGINT CS_FIXED GENERATED BY DEFAULT AS IDENTITY,
    "BaseId" BIGINT CS_FIXED,
    "BaseDetId" INTEGER CS_INT,
    "BaseType" NVARCHAR(50),
    "ItemCode" NVARCHAR(50),
    "ItemName" NVARCHAR(200),
    "FromWhsCode" NVARCHAR(50),
    "FromWhsName" VARCHAR(100),
    "ToWhsCode" NVARCHAR(50),
    "ToWhsName" VARCHAR(100),
    "Quantity" DECIMAL(21,2) CS_FIXED,
    "QuantityOpen" DECIMAL(21,2) CS_FIXED,
    "QuantityScan" DECIMAL(21,2) CS_FIXED,
    "QuantityValid" DECIMAL(21,2) CS_FIXED,
    "QuantityPosted" DECIMAL(21,2) CS_FIXED,
    "UomEntry" INTEGER CS_INT,
    "Uom" NVARCHAR(50),
    "Comments" NVARCHAR(254),
    "TransitWhsCode" NVARCHAR(50),
    "TransitWhsName" NVARCHAR(100),
    "CreatedDate" LONGDATE CS_LONGDATE,
    "CreatedUser" INTEGER CS_INT,
    "ModifiedDate" LONGDATE CS_LONGDATE,
    "ModifiedUser" INTEGER CS_INT,
    PRIMARY KEY ("DetId")
)
UNLOAD PRIORITY 5
AUTO MERGE;

DROP TABLE "Tx_TransferSummaryOut_Approval";
CREATE COLUMN TABLE "Tx_TransferSummaryOut_Approval"
(
    "Id" INTEGER CS_INT,
    "DetId" INTEGER CS_INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "StageId" INTEGER CS_INT,
    "UserId" INTEGER CS_INT,
    "Step" INTEGER CS_INT,
    "Status" NVARCHAR(50),
    "Comments" NVARCHAR(1000),
    "ActionDate" SECONDDATE CS_SECONDDATE,
    "CreatedDate" SECONDDATE CS_SECONDDATE,
    "CreatedUser" INTEGER CS_INT,
    "ModifiedDate" SECONDDATE CS_SECONDDATE,
    "ModifiedUser" INTEGER CS_INT,
    PRIMARY KEY ("DetId")
)
UNLOAD PRIORITY 5
AUTO MERGE;

DROP TABLE "Tx_TransferSummaryOut_Item";
CREATE COLUMN TABLE "Tx_TransferSummaryOut_Item"
(
    "Id" BIGINT CS_FIXED,
    "DetId" BIGINT CS_FIXED GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "RequestId" BIGINT CS_FIXED,
    "RequestDetId" BIGINT CS_FIXED,
    "BaseType" NVARCHAR(50),
    "ItemCode" NVARCHAR(50),
    "ItemName" NVARCHAR(200),
    "FromWhsCode" NVARCHAR(50),
    "FromWhsName" VARCHAR(100),
    "TransitWhsCode" NVARCHAR(50),
    "TransitWhsName" NVARCHAR(100),
    "ToWhsCode" NVARCHAR(50),
    "ToWhsName" VARCHAR(100),
    "QuantityRequest" DECIMAL(21,2) CS_FIXED,
    "QuantityScan" DECIMAL(21,2) CS_FIXED,
    "QuantityValid" DECIMAL(21,2) CS_FIXED,
    "QuantityPosted" DECIMAL(21,2) CS_FIXED,
    "QuantityToReceipt" DECIMAL(21,2) CS_FIXED,
    "LineStatus" NVARCHAR(50),
    "UomEntry" INTEGER CS_INT,
    "Uom" NVARCHAR(50),
    "Comments" NVARCHAR(254),
    "CreatedDate" LONGDATE CS_LONGDATE,
    "CreatedUser" INTEGER CS_INT,
    "ModifiedDate" LONGDATE CS_LONGDATE,
    "ModifiedUser" INTEGER CS_INT,
    PRIMARY KEY ("DetId")
)
UNLOAD PRIORITY 5
AUTO MERGE;

DROP TABLE "Tx_TransferSummaryOut_Item_Tag";
CREATE COLUMN TABLE "Tx_TransferSummaryOut_Item_Tag"
(
    "Id" BIGINT CS_FIXED,
    "DetId" BIGINT CS_FIXED,
    "DetDetId" BIGINT CS_FIXED GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "ItemCode" NVARCHAR(50),
    "ItemName" NVARCHAR(200),
    "TagId" NVARCHAR(200),
    "Quantity" DECIMAL(21,6) CS_FIXED,
    "EventType" NVARCHAR(100),
    "Status" NVARCHAR(50),
    "BaseId" BIGINT CS_FIXED,
    "BaseDetId" BIGINT CS_FIXED,
    "BaseDetDetId" BIGINT CS_FIXED,
    "CreatedDate" LONGDATE CS_LONGDATE,
    "CreatedUser" INTEGER CS_INT,
    "ModifiedDate" LONGDATE CS_LONGDATE,
    "ModifiedUser" INTEGER CS_INT,
    PRIMARY KEY ("DetDetId")
)
UNLOAD PRIORITY 5
AUTO MERGE;

DROP TABLE "Tx_TransferSummaryOut_Ref";
CREATE COLUMN TABLE "Tx_TransferSummaryOut_Ref"
(
    "Id" BIGINT CS_FIXED,
    "DetId" BIGINT CS_FIXED GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "BaseId" NVARCHAR(50),
    "BaseNo" NVARCHAR(200),
    "ScanDeviceId" NVARCHAR(1000),
    "Comments" NVARCHAR(254),
    "Status" NVARCHAR(50),
    "BaseCreatedDate" LONGDATE CS_LONGDATE,
    "BaseCreatedUser" INTEGER CS_INT,
    "CreatedDate" LONGDATE CS_LONGDATE,
    "CreatedUser" INTEGER CS_INT,
    "ModifiedDate" LONGDATE CS_LONGDATE,
    "ModifiedUser" INTEGER CS_INT,
    PRIMARY KEY ("DetId")
)
UNLOAD PRIORITY 5
AUTO MERGE;



DROP TABLE "Tx_ChangeItem";
CREATE TABLE "Tx_ChangeItem" (
    "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    "TransType" NVARCHAR(50),
    "TransNo" NVARCHAR(50),
    "TransDate" TIMESTAMP,
    "WhsCode" NVARCHAR(50),
    "WhsName" VARCHAR(100),
    
    "OriginItemCode" NVARCHAR(50),
    "OriginItemName" NVARCHAR(200),
    "ToItemCode" NVARCHAR(50),
    "ToItemName" NVARCHAR(200),
    
    "Status" NVARCHAR(50),
    "ApprovalStatus" NVARCHAR(50),
    "IsAfterPosted" CHAR(1),
    "Comments" NVARCHAR(254),
    "CancelReason" NVARCHAR(500),
    "IsApproval" CHAR(1),
    "ApprovalMessages" NVARCHAR(254),

    "CreatedDate" TIMESTAMP,
    "CreatedUser" INTEGER,
    "ModifiedDate" TIMESTAMP,
    "ModifiedUser" INTEGER
);

DROP TABLE "Tx_ChangeItem_Tag";
CREATE TABLE "Tx_ChangeItem_Tag" (
    "Id" BIGINT,
    "DetId" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	"TagId" NVARCHAR(200),
    "Comments" NVARCHAR(254),
    "CreatedDate" TIMESTAMP,
    "CreatedUser" INTEGER,
    "ModifiedDate" TIMESTAMP,
    "ModifiedUser" INTEGER
);


