//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MJL_DI.Models._EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tm_Layout
    {
        public int Id { get; set; }
        public string TransType { get; set; }
        public string LayoutFormCode { get; set; }
        public string LayoutName { get; set; }
        public string Description { get; set; }
        public string Uid { get; set; }
        public byte[] Data { get; set; }
        public string OutputType { get; set; }
        public string IsActive { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedUser { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedUser { get; set; }
    }
}
