//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MJL_DI.Models._EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tm_Report_Param
    {
        public Nullable<int> Id { get; set; }
        public int DetId { get; set; }
        public string ParamName { get; set; }
        public string IsMandatory { get; set; }
        public string TypeData { get; set; }
        public string Caption { get; set; }
        public string Sql { get; set; }
        public string TypeControl { get; set; }
        public string TypeChoose { get; set; }
        public string SortCode { get; set; }
        public string IsHide { get; set; }
        public string DefaultValue { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedUser { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedUser { get; set; }
    }
}
