//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MJL_DI.Models._EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ts_List
    {
        public string Type { get; set; }
        public string Sort { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string Category { get; set; }
    }
}
