//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MJL_DI.Models._EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ts_Menu
    {
        public string MenuCode { get; set; }
        public string MenuName { get; set; }
        public string Url { get; set; }
        public string ParentCode { get; set; }
        public string Sort { get; set; }
    }
}
