//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MJL_DI.Models._EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tx_ApprovalMR
    {
        public long Id { get; set; }
        public string TransType { get; set; }
        public string TransNo { get; set; }
        public Nullable<System.DateTime> TransDate { get; set; }
        public Nullable<long> BaseTransId { get; set; }
        public string BaseTransNo { get; set; }
        public Nullable<int> RequesterId { get; set; }
        public string RequesterUserName { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public Nullable<int> ShipId { get; set; }
        public string ShipName { get; set; }
        public string ShipSection { get; set; }
        public string WarehouseCode { get; set; }
        public string WarehouseName { get; set; }
        public string ReqType { get; set; }
        public Nullable<System.DateTime> ReqDate { get; set; }
        public Nullable<int> Attachment { get; set; }
        public string Status { get; set; }
        public string Remark { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedUser { get; set; }
        public Nullable<int> ModifiedUser { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<long> SapDocEntry { get; set; }
        public Nullable<long> SapDocNum { get; set; }
        public string IsAfterPosted { get; set; }
        public string IsApproved { get; set; }
        public string ShipCode { get; set; }
        public string PriceMode { get; set; }
    }
}
