//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MJL_DI.Models._EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tx_AdjustmentIn_Location
    {
        public Nullable<long> Id { get; set; }
        public long DetId { get; set; }
        public Nullable<int> BinAbsEntry { get; set; }
        public string BinCode { get; set; }
        public Nullable<decimal> TotalReceipt { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedUser { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedUser { get; set; }
    }
}
