//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MJL_DI.Models._EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tx_InventoryIn_Detail_Batch
    {
        public Nullable<long> Id { get; set; }
        public Nullable<long> DetId { get; set; }
        public long DetDetId { get; set; }
        public string ItemCode { get; set; }
        public Nullable<int> BaseLine { get; set; }
        public string BatchNum { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<System.DateTime> ExpDate { get; set; }
    }
}
