//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MJL_DI.Models._EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tx_LoadingOrder_SalesOrder
    {
        public Nullable<long> Id { get; set; }
        public long DetId { get; set; }
        public string BaseOwner { get; set; }
        public string BaseType { get; set; }
        public Nullable<long> BaseId { get; set; }
        public string BaseSoNo { get; set; }
        public Nullable<System.DateTime> BaseSoDate { get; set; }
        public string CustomerCode { get; set; }
        public string CustomerName { get; set; }
        public string ItemCode { get; set; }
        public string ItemName { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<decimal> OpenQuantity { get; set; }
        public string Destination { get; set; }
        public Nullable<decimal> Capacity { get; set; }
        public string RemarksInternal { get; set; }
        public string Description { get; set; }
        public Nullable<long> SapDeliveryId { get; set; }
        public string SapDeliveryNo { get; set; }
        public Nullable<long> SapGoodIssueId { get; set; }
        public string SapGoodIssueNo { get; set; }
        public Nullable<long> SapGoodReceiptId { get; set; }
        public string SapGoodReceiptNo { get; set; }
        public Nullable<decimal> QtyDeliver { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedUser { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedUser { get; set; }
        public Nullable<long> SapInventoryTransferId { get; set; }
        public string SapInventoryTransferNo { get; set; }
        public Nullable<long> SapInventoryTransferCancelId { get; set; }
        public string SapInventoryTransferCancelNo { get; set; }
    }
}
