//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MJL_DI.Models._EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tx_LoadingOrder
    {
        public long Id { get; set; }
        public string TransType { get; set; }
        public string TransNo { get; set; }
        public Nullable<System.DateTime> TransDate { get; set; }
        public string WarehouseCode { get; set; }
        public string WarehouseName { get; set; }
        public string ShippingType { get; set; }
        public string Owner { get; set; }
        public string Status { get; set; }
        public Nullable<decimal> PreferedCapacity { get; set; }
        public Nullable<int> UnitId { get; set; }
        public string UnitName { get; set; }
        public string UnitPoliceNo { get; set; }
        public Nullable<decimal> UnitCapacity { get; set; }
        public Nullable<int> DriverId { get; set; }
        public string DriverName { get; set; }
        public Nullable<int> SegelQuantity { get; set; }
        public string IsUseTangkiJalan { get; set; }
        public Nullable<decimal> TangkiJalanCapacity { get; set; }
        public string IsAfterPosted { get; set; }
        public string IsAfterDelivered { get; set; }
        public Nullable<decimal> RealisasiTangkiJalan { get; set; }
        public Nullable<decimal> RealisasiTemp { get; set; }
        public Nullable<decimal> RealisasiSg { get; set; }
        public Nullable<decimal> RealisasiT2DpnBlkg { get; set; }
        public string RealisasiFSBinCode { get; set; }
        public Nullable<int> RealisasiFSBinAbsEntry { get; set; }
        public string RealisasiTJBinCode { get; set; }
        public Nullable<int> RealisasiTJBinAbsEntry { get; set; }
        public string IsReturnTJ { get; set; }
        public Nullable<System.DateTime> DeliverDate { get; set; }
        public Nullable<System.DateTime> ReceiptDate { get; set; }
        public string CancelReason { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedUser { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedUser { get; set; }
        public string SppOwner { get; set; }
        public Nullable<long> SppId { get; set; }
        public string SppNo { get; set; }
        public string SppType { get; set; }
        public Nullable<long> SapDeliveryTJId { get; set; }
        public string SapDeliveryTJNo { get; set; }
        public string IsSyncDlvryBiayaAngkut { get; set; }
        public string SyncDlvryBiayaAngkutOwner { get; set; }
        public Nullable<long> SyncDlvryBiayaAngkutId { get; set; }
        public string SyncDlvryBiayaAngkutNo { get; set; }
        public string SyncDlvryBiayaAngkutError { get; set; }
        public string IsNewRoute { get; set; }
        public string IsNewUnit { get; set; }
        public Nullable<long> OldSppRouteId { get; set; }
        public string OldSppRouteNo { get; set; }
        public Nullable<long> OldSppUnitId { get; set; }
        public string OldSppUnitNo { get; set; }
        public Nullable<int> TugUnitId { get; set; }
        public string TugUnitNo { get; set; }
        public string TugUnitName { get; set; }
        public string TinggiTerra { get; set; }
        public string RealisasiFSLocation { get; set; }
    }
}
