//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MJL_DI.Models._EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tx_MaterialRequest_Detail
    {
        public Nullable<long> Id { get; set; }
        public long DetId { get; set; }
        public Nullable<int> RowNum { get; set; }
        public string ItemCode { get; set; }
        public string ItemDescription { get; set; }
        public Nullable<int> Qty { get; set; }
        public string UoMCode { get; set; }
        public Nullable<int> ROB { get; set; }
        public string Remark { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedUser { get; set; }
        public Nullable<int> ModifiedUser { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<long> SapDocEntry { get; set; }
        public Nullable<long> SapDocNum { get; set; }
        public Nullable<int> UomEntry { get; set; }
    }
}
