//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MJL_DI.Models._EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tx_TukarFakturReceipt
    {
        public long Id { get; set; }
        public string NoTglTerima { get; set; }
        public Nullable<System.DateTime> TglTerima { get; set; }
        public string NoTtd { get; set; }
        public string NamaPenerima { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedUser { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedUser { get; set; }
        public string Resi { get; set; }
        public string Keterangan { get; set; }
        public string MetodeKirim { get; set; }
        public string Pengiriman { get; set; }
    }
}
