//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MJL_DI.Models._EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tx_TukarFakturSend
    {
        public long Id { get; set; }
        public string NoDokumen { get; set; }
        public Nullable<System.DateTime> TglDokumen { get; set; }
        public string MetodeKirim { get; set; }
        public string Pengiriman { get; set; }
        public string NamaCustomer { get; set; }
        public string AlamatKirim { get; set; }
        public string NoInvoice { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedUser { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedUser { get; set; }
        public string CodeCustomer { get; set; }
    }
}
