//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESKA_DI.Models._EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HANA_APP : DbContext
    {
        public HANA_APP()
            : base("name=HANA_APP")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Tm_Alert> Tm_Alert { get; set; }
        public virtual DbSet<Tm_Alert_Role> Tm_Alert_Role { get; set; }
        public virtual DbSet<Tm_Alert_User> Tm_Alert_User { get; set; }
        public virtual DbSet<Tm_AlertGroup> Tm_AlertGroup { get; set; }
        public virtual DbSet<Tm_Approval> Tm_Approval { get; set; }
        public virtual DbSet<Tm_Approval_Role> Tm_Approval_Role { get; set; }
        public virtual DbSet<Tm_Approval_User> Tm_Approval_User { get; set; }
        public virtual DbSet<Tm_ApprovalStage> Tm_ApprovalStage { get; set; }
        public virtual DbSet<Tm_ApprovalStage_Role> Tm_ApprovalStage_Role { get; set; }
        public virtual DbSet<Tm_ApprovalStage_User> Tm_ApprovalStage_User { get; set; }
        public virtual DbSet<Tm_ApprovalTemplate> Tm_ApprovalTemplate { get; set; }
        public virtual DbSet<Tm_ApprovalTemplate_Position> Tm_ApprovalTemplate_Position { get; set; }
        public virtual DbSet<Tm_ApprovalTemplate_Role> Tm_ApprovalTemplate_Role { get; set; }
        public virtual DbSet<Tm_ApprovalTemplate_Stage> Tm_ApprovalTemplate_Stage { get; set; }
        public virtual DbSet<Tm_ApprovalTemplate_User> Tm_ApprovalTemplate_User { get; set; }
        public virtual DbSet<Tm_GeneralSetting> Tm_GeneralSetting { get; set; }
        public virtual DbSet<Tm_GeneralSetting_Coa> Tm_GeneralSetting_Coa { get; set; }
        public virtual DbSet<Tm_GeneralSetting_Item> Tm_GeneralSetting_Item { get; set; }
        public virtual DbSet<Tm_Item> Tm_Item { get; set; }
        public virtual DbSet<Tm_Item_Warehouse> Tm_Item_Warehouse { get; set; }
        public virtual DbSet<Tm_Item_Warehouse_Tag> Tm_Item_Warehouse_Tag { get; set; }
        public virtual DbSet<Tm_Item_Warehouse_Tag_Log> Tm_Item_Warehouse_Tag_Log { get; set; }
        public virtual DbSet<Tm_Item_Warehouse_Tag_Replace> Tm_Item_Warehouse_Tag_Replace { get; set; }
        public virtual DbSet<Tm_Layout> Tm_Layout { get; set; }
        public virtual DbSet<Tm_Layout_Role> Tm_Layout_Role { get; set; }
        public virtual DbSet<Tm_Layout_User> Tm_Layout_User { get; set; }
        public virtual DbSet<Tm_MasterSetting> Tm_MasterSetting { get; set; }
        public virtual DbSet<Tm_Position> Tm_Position { get; set; }
        public virtual DbSet<Tm_Query> Tm_Query { get; set; }
        public virtual DbSet<Tm_Query_Param> Tm_Query_Param { get; set; }
        public virtual DbSet<Tm_Query_Role> Tm_Query_Role { get; set; }
        public virtual DbSet<Tm_Query_User> Tm_Query_User { get; set; }
        public virtual DbSet<Tm_QueryGroup> Tm_QueryGroup { get; set; }
        public virtual DbSet<Tm_QueryGroup_Role> Tm_QueryGroup_Role { get; set; }
        public virtual DbSet<Tm_QueryGroup_User> Tm_QueryGroup_User { get; set; }
        public virtual DbSet<Tm_Report> Tm_Report { get; set; }
        public virtual DbSet<Tm_Report_Param> Tm_Report_Param { get; set; }
        public virtual DbSet<Tm_Report_Role> Tm_Report_Role { get; set; }
        public virtual DbSet<Tm_Report_User> Tm_Report_User { get; set; }
        public virtual DbSet<Tm_ReportGroup> Tm_ReportGroup { get; set; }
        public virtual DbSet<Tm_ReportGroup_Role> Tm_ReportGroup_Role { get; set; }
        public virtual DbSet<Tm_ReportGroup_User> Tm_ReportGroup_User { get; set; }
        public virtual DbSet<Tm_Role> Tm_Role { get; set; }
        public virtual DbSet<Tm_Role_Auth> Tm_Role_Auth { get; set; }
        public virtual DbSet<Tm_User> Tm_User { get; set; }
        public virtual DbSet<Tm_User_Routing> Tm_User_Routing { get; set; }
        public virtual DbSet<Tp_Approval> Tp_Approval { get; set; }
        public virtual DbSet<Ts_FormatNumbering> Ts_FormatNumbering { get; set; }
        public virtual DbSet<Ts_LayoutForm> Ts_LayoutForm { get; set; }
        public virtual DbSet<Ts_List> Ts_List { get; set; }
        public virtual DbSet<Ts_Menu> Ts_Menu { get; set; }
        public virtual DbSet<Ts_ObjectApproval> Ts_ObjectApproval { get; set; }
        public virtual DbSet<Tx_GoodsReceiptPO> Tx_GoodsReceiptPO { get; set; }
        public virtual DbSet<Tx_GoodsReceiptPO_Item> Tx_GoodsReceiptPO_Item { get; set; }
        public virtual DbSet<Tx_GoodsReceiptPO_Item_Batch> Tx_GoodsReceiptPO_Item_Batch { get; set; }
        public virtual DbSet<Tx_GoodsReceiptPO_Item_Batch_Scale> Tx_GoodsReceiptPO_Item_Batch_Scale { get; set; }
        public virtual DbSet<Tx_ProcessCard> Tx_ProcessCard { get; set; }
        public virtual DbSet<Tx_StockOpname> Tx_StockOpname { get; set; }
        public virtual DbSet<Tx_StockOpname_Approval> Tx_StockOpname_Approval { get; set; }
        public virtual DbSet<Tx_StockOpname_Item> Tx_StockOpname_Item { get; set; }
        public virtual DbSet<Tp_UserAlert> Tp_UserAlert { get; set; }
        public virtual DbSet<Tx_ProcessCard_Detail> Tx_ProcessCard_Detail { get; set; }
    }
}
