//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BBS_DI.Models._EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HANA_APP : DbContext
    {
        public HANA_APP()
            : base("name=HANA_APP")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Tm_Alert> Tm_Alert { get; set; }
        public virtual DbSet<Tm_Alert_Role> Tm_Alert_Role { get; set; }
        public virtual DbSet<Tm_Alert_User> Tm_Alert_User { get; set; }
        public virtual DbSet<Tm_AlertGroup> Tm_AlertGroup { get; set; }
        public virtual DbSet<Tm_Approval> Tm_Approval { get; set; }
        public virtual DbSet<Tm_Approval_Role> Tm_Approval_Role { get; set; }
        public virtual DbSet<Tm_Approval_User> Tm_Approval_User { get; set; }
        public virtual DbSet<Tm_ApprovalStage> Tm_ApprovalStage { get; set; }
        public virtual DbSet<Tm_ApprovalStage_Role> Tm_ApprovalStage_Role { get; set; }
        public virtual DbSet<Tm_ApprovalStage_User> Tm_ApprovalStage_User { get; set; }
        public virtual DbSet<Tm_ApprovalTemplate> Tm_ApprovalTemplate { get; set; }
        public virtual DbSet<Tm_ApprovalTemplate_Position> Tm_ApprovalTemplate_Position { get; set; }
        public virtual DbSet<Tm_ApprovalTemplate_Role> Tm_ApprovalTemplate_Role { get; set; }
        public virtual DbSet<Tm_ApprovalTemplate_Stage> Tm_ApprovalTemplate_Stage { get; set; }
        public virtual DbSet<Tm_ApprovalTemplate_User> Tm_ApprovalTemplate_User { get; set; }
        public virtual DbSet<Tm_GeneralSetting> Tm_GeneralSetting { get; set; }
        public virtual DbSet<Tm_GeneralSetting_Coa> Tm_GeneralSetting_Coa { get; set; }
        public virtual DbSet<Tm_GeneralSetting_Item> Tm_GeneralSetting_Item { get; set; }
        public virtual DbSet<Tm_Item> Tm_Item { get; set; }
        public virtual DbSet<Tm_Item_Warehouse> Tm_Item_Warehouse { get; set; }
        public virtual DbSet<Tm_Item_Warehouse_Tag> Tm_Item_Warehouse_Tag { get; set; }
        public virtual DbSet<Tm_Item_Warehouse_Tag_Log> Tm_Item_Warehouse_Tag_Log { get; set; }
        public virtual DbSet<Tm_Item_Warehouse_Tag_Replace> Tm_Item_Warehouse_Tag_Replace { get; set; }
        public virtual DbSet<Tm_Layout> Tm_Layout { get; set; }
        public virtual DbSet<Tm_Layout_Role> Tm_Layout_Role { get; set; }
        public virtual DbSet<Tm_Layout_User> Tm_Layout_User { get; set; }
        public virtual DbSet<Tm_MasterSetting> Tm_MasterSetting { get; set; }
        public virtual DbSet<Tm_Query> Tm_Query { get; set; }
        public virtual DbSet<Tm_Query_Param> Tm_Query_Param { get; set; }
        public virtual DbSet<Tm_Query_Role> Tm_Query_Role { get; set; }
        public virtual DbSet<Tm_Query_User> Tm_Query_User { get; set; }
        public virtual DbSet<Tm_QueryGroup> Tm_QueryGroup { get; set; }
        public virtual DbSet<Tm_QueryGroup_Role> Tm_QueryGroup_Role { get; set; }
        public virtual DbSet<Tm_QueryGroup_User> Tm_QueryGroup_User { get; set; }
        public virtual DbSet<Tm_Report> Tm_Report { get; set; }
        public virtual DbSet<Tm_Report_Param> Tm_Report_Param { get; set; }
        public virtual DbSet<Tm_Report_Role> Tm_Report_Role { get; set; }
        public virtual DbSet<Tm_Report_User> Tm_Report_User { get; set; }
        public virtual DbSet<Tm_ReportGroup> Tm_ReportGroup { get; set; }
        public virtual DbSet<Tm_ReportGroup_Role> Tm_ReportGroup_Role { get; set; }
        public virtual DbSet<Tm_ReportGroup_User> Tm_ReportGroup_User { get; set; }
        public virtual DbSet<Tm_Role> Tm_Role { get; set; }
        public virtual DbSet<Tm_Role_Auth> Tm_Role_Auth { get; set; }
        public virtual DbSet<Tm_User> Tm_User { get; set; }
        public virtual DbSet<Tm_User_Warehouse> Tm_User_Warehouse { get; set; }
        public virtual DbSet<Tp_Approval> Tp_Approval { get; set; }
        public virtual DbSet<Tp_Approval_User> Tp_Approval_User { get; set; }
        public virtual DbSet<Ts_FormatNumbering> Ts_FormatNumbering { get; set; }
        public virtual DbSet<Ts_LayoutForm> Ts_LayoutForm { get; set; }
        public virtual DbSet<Ts_List> Ts_List { get; set; }
        public virtual DbSet<Ts_Menu> Ts_Menu { get; set; }
        public virtual DbSet<Ts_ObjectApproval> Ts_ObjectApproval { get; set; }
        public virtual DbSet<Tx_AdjustmentIn> Tx_AdjustmentIn { get; set; }
        public virtual DbSet<Tx_AdjustmentIn_Approval> Tx_AdjustmentIn_Approval { get; set; }
        public virtual DbSet<Tx_AdjustmentIn_Attachment> Tx_AdjustmentIn_Attachment { get; set; }
        public virtual DbSet<Tx_AdjustmentIn_Item> Tx_AdjustmentIn_Item { get; set; }
        public virtual DbSet<Tx_AdjustmentIn_Item_Tag> Tx_AdjustmentIn_Item_Tag { get; set; }
        public virtual DbSet<Tx_AdjustmentIn_Location> Tx_AdjustmentIn_Location { get; set; }
        public virtual DbSet<Tx_AdjustmentOut> Tx_AdjustmentOut { get; set; }
        public virtual DbSet<Tx_AdjustmentOut_Approval> Tx_AdjustmentOut_Approval { get; set; }
        public virtual DbSet<Tx_AdjustmentOut_Attachment> Tx_AdjustmentOut_Attachment { get; set; }
        public virtual DbSet<Tx_AdjustmentOut_Item> Tx_AdjustmentOut_Item { get; set; }
        public virtual DbSet<Tx_AdjustmentOut_Item_Tag> Tx_AdjustmentOut_Item_Tag { get; set; }
        public virtual DbSet<Tx_AdjustmentOut_Location> Tx_AdjustmentOut_Location { get; set; }
        public virtual DbSet<Tx_ChangeItem> Tx_ChangeItem { get; set; }
        public virtual DbSet<Tx_ChangeItem_Tag> Tx_ChangeItem_Tag { get; set; }
        public virtual DbSet<Tx_DeactiveTag> Tx_DeactiveTag { get; set; }
        public virtual DbSet<Tx_DeactiveTag_Approval> Tx_DeactiveTag_Approval { get; set; }
        public virtual DbSet<Tx_DeactiveTag_Item> Tx_DeactiveTag_Item { get; set; }
        public virtual DbSet<Tx_DeactiveTag_Log> Tx_DeactiveTag_Log { get; set; }
        public virtual DbSet<Tx_GoodIssue> Tx_GoodIssue { get; set; }
        public virtual DbSet<Tx_GoodsReceiptPO> Tx_GoodsReceiptPO { get; set; }
        public virtual DbSet<Tx_GoodsReceiptPO_Approval> Tx_GoodsReceiptPO_Approval { get; set; }
        public virtual DbSet<Tx_GoodsReceiptPO_Item> Tx_GoodsReceiptPO_Item { get; set; }
        public virtual DbSet<Tx_GoodsReceiptPO_Item_Tag> Tx_GoodsReceiptPO_Item_Tag { get; set; }
        public virtual DbSet<Tx_GoodsReceiptPO_Ref> Tx_GoodsReceiptPO_Ref { get; set; }
        public virtual DbSet<Tx_PurchaseOrder> Tx_PurchaseOrder { get; set; }
        public virtual DbSet<Tx_PurchaseOrder_Item> Tx_PurchaseOrder_Item { get; set; }
        public virtual DbSet<Tx_PurchaseOrder_Item_Tag> Tx_PurchaseOrder_Item_Tag { get; set; }
        public virtual DbSet<Tx_Request_StockOpname> Tx_Request_StockOpname { get; set; }
        public virtual DbSet<Tx_StockOpname> Tx_StockOpname { get; set; }
        public virtual DbSet<Tx_StockOpname_Approval> Tx_StockOpname_Approval { get; set; }
        public virtual DbSet<Tx_StockOpname_Item> Tx_StockOpname_Item { get; set; }
        public virtual DbSet<Tx_StockOpname_Item_Tag> Tx_StockOpname_Item_Tag { get; set; }
        public virtual DbSet<Tx_StockSummaryOpname> Tx_StockSummaryOpname { get; set; }
        public virtual DbSet<Tx_StockSummaryOpname_Approval> Tx_StockSummaryOpname_Approval { get; set; }
        public virtual DbSet<Tx_StockSummaryOpname_Item> Tx_StockSummaryOpname_Item { get; set; }
        public virtual DbSet<Tx_StockSummaryOpname_Item_Tag> Tx_StockSummaryOpname_Item_Tag { get; set; }
        public virtual DbSet<Tx_StockSummaryOpname_Ref> Tx_StockSummaryOpname_Ref { get; set; }
        public virtual DbSet<Tx_TransferIn> Tx_TransferIn { get; set; }
        public virtual DbSet<Tx_TransferIn_Item> Tx_TransferIn_Item { get; set; }
        public virtual DbSet<Tx_TransferIn_Item_Tag> Tx_TransferIn_Item_Tag { get; set; }
        public virtual DbSet<Tx_TransferOut> Tx_TransferOut { get; set; }
        public virtual DbSet<Tx_TransferOut_Item> Tx_TransferOut_Item { get; set; }
        public virtual DbSet<Tx_TransferOut_Item_Tag> Tx_TransferOut_Item_Tag { get; set; }
        public virtual DbSet<Tx_TransferRequest> Tx_TransferRequest { get; set; }
        public virtual DbSet<Tx_TransferRequest_Approval> Tx_TransferRequest_Approval { get; set; }
        public virtual DbSet<Tx_TransferRequest_Item> Tx_TransferRequest_Item { get; set; }
        public virtual DbSet<Tx_TransferSummaryIn> Tx_TransferSummaryIn { get; set; }
        public virtual DbSet<Tx_TransferSummaryIn_Approval> Tx_TransferSummaryIn_Approval { get; set; }
        public virtual DbSet<Tx_TransferSummaryIn_Item> Tx_TransferSummaryIn_Item { get; set; }
        public virtual DbSet<Tx_TransferSummaryIn_Item_Tag> Tx_TransferSummaryIn_Item_Tag { get; set; }
        public virtual DbSet<Tx_TransferSummaryIn_Ref> Tx_TransferSummaryIn_Ref { get; set; }
        public virtual DbSet<Tx_TransferSummaryOut> Tx_TransferSummaryOut { get; set; }
        public virtual DbSet<Tx_TransferSummaryOut_Approval> Tx_TransferSummaryOut_Approval { get; set; }
        public virtual DbSet<Tx_TransferSummaryOut_Item> Tx_TransferSummaryOut_Item { get; set; }
        public virtual DbSet<Tx_TransferSummaryOut_Item_Tag> Tx_TransferSummaryOut_Item_Tag { get; set; }
        public virtual DbSet<Tx_TransferSummaryOut_Ref> Tx_TransferSummaryOut_Ref { get; set; }
        public virtual DbSet<Tp_UserAlert> Tp_UserAlert { get; set; }
    }
}
