//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BBS_DI.Models._EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tm_DocContent
    {
        public int Id { get; set; }
        public string TransType { get; set; }
        public string DocumentName { get; set; }
        public string Type { get; set; }
        public string IsActive { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedUser { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedUser { get; set; }
        public string ExpiredType { get; set; }
        public Nullable<int> WarningNotif { get; set; }
    }
}
