//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESKA_DI.Models._EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tm_Item_Warehouse_Tag_Log
    {
        public long LogId { get; set; }
        public string BaseType { get; set; }
        public string ItemCode { get; set; }
        public string ItemName { get; set; }
        public string WhsCode { get; set; }
        public string WhsName { get; set; }
        public string OldTagId { get; set; }
        public string NewTagId { get; set; }
        public string OldStatus { get; set; }
        public string NewStatus { get; set; }
        public string Event { get; set; }
        public string ActionNote { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedUser { get; set; }
        public string NewItemCode { get; set; }
        public string NewItemName { get; set; }
        public Nullable<long> BaseId { get; set; }
        public string BaseTransNo { get; set; }
    }
}
