//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BBS_DI.Models._EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tm_MasterSetting_Item
    {
        public long Id { get; set; }
        public string Bagian { get; set; }
        public string Item { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> EstTime { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedUser { get; set; }
        public Nullable<int> ModifiedUser { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}
