//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BBS_DI.Models._EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tm_Role_Auth
    {
        public Nullable<int> Id { get; set; }
        public int DetId { get; set; }
        public string MenuCode { get; set; }
        public string IsAccess { get; set; }
    }
}
