//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BBS_DI.Models._EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tm_Ship
    {
        public long Id { get; set; }
        public string ShipName { get; set; }
        public string Alias { get; set; }
        public string ShipType { get; set; }
        public string Builder { get; set; }
        public string YearOfBuild { get; set; }
        public string Flag { get; set; }
        public string Class { get; set; }
        public string CallSign { get; set; }
        public string RegMark { get; set; }
        public string RegPlace { get; set; }
        public Nullable<decimal> LOA { get; set; }
        public Nullable<decimal> LBP { get; set; }
        public Nullable<decimal> BreadthMoulded { get; set; }
        public Nullable<decimal> DepthDraught { get; set; }
        public Nullable<decimal> GrossTonnage { get; set; }
        public Nullable<decimal> NetTonnage { get; set; }
        public Nullable<decimal> DraftDesign { get; set; }
        public string Owner { get; set; }
        public string OwnerAddress { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedUser { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string MarkTonnage { get; set; }
        public Nullable<int> ModifiedUser { get; set; }
        public string ShipCode { get; set; }
        public string MarkOfTonageCer { get; set; }
    }
}
