//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BBS_DI.Models._EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tm_Ship_Engine
    {
        public Nullable<long> Id { get; set; }
        public long DetId { get; set; }
        public string DetName { get; set; }
        public string Brand { get; set; }
        public string Power { get; set; }
        public string StdLO { get; set; }
        public string StdFilterLO { get; set; }
        public string StdFORacor { get; set; }
        public string StdFOFilter { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedUser { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> Modifieduser { get; set; }
    }
}
