//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESKA_DI.Models._EF
{
    using System;
    using System.Collections.Generic;

    public partial class Tp_ScaleStaging
    {
        public long StagingId { get; set; }
        public string TransType { get; set; }
        public long Id { get; set; }
        public Nullable<long> DetId { get; set; }
        public Nullable<long> DetDetId { get; set; }
        public Nullable<long> DetDetDetId { get; set; }
        public string TransNo { get; set; }
        public string DocNum { get; set; }
        public string ItemCode { get; set; }
        public string ItemName { get; set; }
        public string WhsCode { get; set; }
        public string Batch { get; set; }
        public Nullable<int> BatchLineNum { get; set; }
        public Nullable<int> ScaleLineNum { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public string Uom { get; set; }
        public Nullable<decimal> Netto { get; set; }
        public Nullable<decimal> WeightKg { get; set; }
        public string ScaleStatus { get; set; }
        public string Status { get; set; }
        public string RequestId { get; set; }
        public Nullable<System.DateTime> SentDate { get; set; }
        public Nullable<System.DateTime> ResponseDate { get; set; }
        public Nullable<int> RetryCount { get; set; }
        public string ErrorMessage { get; set; }
        public string RequestPayload { get; set; }
        public string ResponsePayload { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedUser { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedUser { get; set; }
    }
}
