//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BBS_DI.Models._EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tp_UserAlert
    {
        public long Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public string BaseType { get; set; }
        public Nullable<long> BaseId { get; set; }
        public string BaseTransNo { get; set; }
        public string Action { get; set; }
        public string NotificationMessage { get; set; }
        public Nullable<int> SenderId { get; set; }
        public string IsRead { get; set; }
        public Nullable<System.DateTime> LastShowTime { get; set; }
    }
}
