//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESKA_DI.Models._EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tx_AdjustmentIn_Item
    {
        public long Id { get; set; }
        public long DetId { get; set; }
        public string ItemCode { get; set; }
        public string ItemName { get; set; }
        public string FreeText { get; set; }
        public string WhsCode { get; set; }
        public string PillarsCode { get; set; }
        public string PillarsName { get; set; }
        public string ClassCode { get; set; }
        public string ClassName { get; set; }
        public string SubClass1Code { get; set; }
        public string SubClass1Name { get; set; }
        public string SubClass2Code { get; set; }
        public string SubClass2Name { get; set; }
        public string ProjectCode { get; set; }
        public string ProjectName { get; set; }
        public Nullable<decimal> QuantityScan { get; set; }
        public Nullable<decimal> QuantityPosted { get; set; }
        public string LineStatus { get; set; }
        public Nullable<decimal> UnitPriceTc { get; set; }
        public Nullable<int> UomEntry { get; set; }
        public string Uom { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedUser { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedUser { get; set; }
    }
}
