//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESKA_DI.Models._EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tx_AdjustmentIn
    {
        public long Id { get; set; }
        public string TransType { get; set; }
        public string TransNo { get; set; }
        public Nullable<System.DateTime> TransDate { get; set; }
        public Nullable<System.DateTime> PostingDate { get; set; }
        public string AdjustmentTypeCode { get; set; }
        public string AdjustmentTypeName { get; set; }
        public string PillarsCode { get; set; }
        public string PillarsName { get; set; }
        public string ClassCode { get; set; }
        public string ClassName { get; set; }
        public string SubClass1Code { get; set; }
        public string SubClass1Name { get; set; }
        public string SubClass2Code { get; set; }
        public string SubClass2Name { get; set; }
        public string ProjectCode { get; set; }
        public string ProjectName { get; set; }
        public string Status { get; set; }
        public string ApprovalStatus { get; set; }
        public string IsAfterPosted { get; set; }
        public string IsOpeningBalance { get; set; }
        public Nullable<int> DocEntry { get; set; }
        public string Comments { get; set; }
        public string ScanDeviceId { get; set; }
        public string WhsCode { get; set; }
        public string CancelReason { get; set; }
        public string IsApproval { get; set; }
        public string ApprovalMessages { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedUser { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedUser { get; set; }
    }
}
