//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BBS_DI.Models._EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tx_ApprovalMR_Detail
    {
        public Nullable<long> Id { get; set; }
        public long DetId { get; set; }
        public Nullable<long> BaseDetID { get; set; }
        public Nullable<int> RowNum { get; set; }
        public string ItemCode { get; set; }
        public string ItemDescription { get; set; }
        public Nullable<decimal> Qty { get; set; }
        public Nullable<int> UomEntry { get; set; }
        public string UoMCode { get; set; }
        public Nullable<decimal> ROB { get; set; }
        public string Remark { get; set; }
        public Nullable<decimal> QtyVA { get; set; }
        public Nullable<decimal> QtyApproved { get; set; }
        public string IsApproved { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public Nullable<decimal> WhsQty { get; set; }
        public Nullable<long> DocEntryPR { get; set; }
        public string DocNumPR { get; set; }
        public Nullable<decimal> QtyPR { get; set; }
        public Nullable<long> DocEntryPO { get; set; }
        public string DocNumPO { get; set; }
        public Nullable<decimal> QtyPO { get; set; }
        public string IsAfterPosted { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedUser { get; set; }
        public Nullable<int> ModifiedUser { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string Remark2 { get; set; }
        public Nullable<decimal> QtySJ { get; set; }
        public string ItemRemark { get; set; }
    }
}
