//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESKA_DI.Models._EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tx_AdjustmentOut_Item_Tag
    {
        public Nullable<long> Id { get; set; }
        public Nullable<long> DetId { get; set; }
        public long DetDetId { get; set; }
        public string ItemCode { get; set; }
        public string ItemName { get; set; }
        public string TagId { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public string EventType { get; set; }
        public string Status { get; set; }
        public string PostResultNote { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedUser { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedUser { get; set; }
    }
}
