//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BBS_DI.Models._EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tx_Docking_Detail
    {
        public Nullable<long> Id { get; set; }
        public long DetId { get; set; }
        public Nullable<int> RowNum { get; set; }
        public string Bagian { get; set; }
        public string Item { get; set; }
        public string SubItem { get; set; }
        public string Kerusakan { get; set; }
        public string Perbaikan { get; set; }
        public string Material { get; set; }
        public Nullable<decimal> EstTime { get; set; }
        public string PIC { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string Status { get; set; }
        public string Remark { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedUser { get; set; }
        public Nullable<int> ModifiedUser { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}
