//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BBS_DI.Models._EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tx_GoodIssue_Detail
    {
        public Nullable<long> Id { get; set; }
        public long DetId { get; set; }
        public Nullable<long> BaseDetID { get; set; }
        public Nullable<int> RowNum { get; set; }
        public string ItemCode { get; set; }
        public string ItemDescription { get; set; }
        public Nullable<decimal> Qty { get; set; }
        public Nullable<int> UomEntry { get; set; }
        public string UoMCode { get; set; }
        public Nullable<decimal> ROB { get; set; }
        public string Remark { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedUser { get; set; }
        public Nullable<int> ModifiedUser { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ManBtchNum { get; set; }
        public string Batch { get; set; }
        public string ItemRemark { get; set; }
    }
}
