//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESKA_DI.Models._EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tx_GoodsReceiptPO
    {
        public long Id { get; set; }
        public string TransType { get; set; }
        public string TransNo { get; set; }
        public Nullable<System.DateTime> TransDate { get; set; }
        public string VendorCode { get; set; }
        public string VendorName { get; set; }
        public string Address { get; set; }
        public Nullable<long> DocEntry { get; set; }
        public string DocNum { get; set; }
        public Nullable<System.DateTime> DocDate { get; set; }
        public string RefNo { get; set; }
        public string Status { get; set; }
        public string ApprovalStatus { get; set; }
        public Nullable<long> BaseEntry { get; set; }
        public string BaseDocNum { get; set; }
        public Nullable<System.DateTime> PostingDate { get; set; }
        public string IsAfterPosted { get; set; }
        public string Comments { get; set; }
        public string CancelReason { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedUser { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedUser { get; set; }
        public string ApprovalMessages { get; set; }
        public string IsApproval { get; set; }
    }
}
