//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESKA_DI.Models._EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tx_GoodsReceiptPO_Item
    {
        public Nullable<long> Id { get; set; }
        public long DetId { get; set; }
        public string ItemCode { get; set; }
        public string ItemName { get; set; }
        public string WhsCode { get; set; }
        public Nullable<decimal> QuantityOnHandSAP { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<decimal> QuantityOpen { get; set; }
        public Nullable<decimal> QuantityScan { get; set; }
        public Nullable<decimal> QuantityValid { get; set; }
        public Nullable<decimal> UnitPriceTc { get; set; }
        public Nullable<int> UomEntry { get; set; }
        public string Uom { get; set; }
        public Nullable<long> DocEntry { get; set; }
        public string DocNum { get; set; }
        public Nullable<int> LineNum { get; set; }
        public Nullable<long> BaseEntry { get; set; }
        public Nullable<int> BaseLine { get; set; }
        public string LineStatus { get; set; }
        public Nullable<int> IdPDO { get; set; }
        public Nullable<int> GoodsReceiptDocEntry { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedUser { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedUser { get; set; }
    }
}
