//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BBS_DI.Models._EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tx_InventoryIn_Detail
    {
        public Nullable<long> Id { get; set; }
        public long DetId { get; set; }
        public string ItemCode { get; set; }
        public string ItemDescription { get; set; }
        public Nullable<System.DateTime> TransDate { get; set; }
        public Nullable<int> UomEntry { get; set; }
        public string UoMCode { get; set; }
        public Nullable<decimal> QtyOrder { get; set; }
        public Nullable<decimal> QtyReceipt { get; set; }
        public Nullable<int> SapPoId { get; set; }
        public string SapPoNo { get; set; }
        public string SapPoLineNum { get; set; }
        public Nullable<int> ShipId { get; set; }
        public string ShipName { get; set; }
        public Nullable<int> MRId { get; set; }
        public string MRNum { get; set; }
        public string Status { get; set; }
        public string Batch { get; set; }
        public string Remark { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedUser { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedUser { get; set; }
        public string ManBtchNum { get; set; }
        public Nullable<decimal> QtyOpen { get; set; }
        public string BatchName { get; set; }
        public string ItemRemark { get; set; }
    }
}
