//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESKA_DI.Models._EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tx_IssueAndReceipt
    {
        public long Id { get; set; }
        public string TransType { get; set; }
        public string TransNo { get; set; }
        public Nullable<System.DateTime> TransDate { get; set; }
        public Nullable<long> IssueDocEntry { get; set; }
        public string IssueDocNum { get; set; }
        public Nullable<System.DateTime> IssueDocDate { get; set; }
        public Nullable<long> ReceiptDocEntry { get; set; }
        public string ReceiptDocNum { get; set; }
        public Nullable<System.DateTime> ReceiptDocDate { get; set; }
        public Nullable<System.DateTime> PostingDate { get; set; }
        public Nullable<long> BaseEntry { get; set; }
        public string BaseDocNum { get; set; }
        public string BaseProcessCardTransNo { get; set; }
        public Nullable<long> BaseProcessCardId { get; set; }
        public Nullable<int> BaseProcessCardSort { get; set; }
        public string BaseProcessCardRoutingCode { get; set; }
        public string BaseProcessCardRoutingName { get; set; }
        public Nullable<int> BaseProcessCardOperatorId { get; set; }
        public string BaseProcessCardOperatorName { get; set; }
        public string IsAfterPosted { get; set; }
        public string CancelReason { get; set; }
        public string RefNo { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> CreatedUser { get; set; }
        public Nullable<int> ModifiedUser { get; set; }
    }
}
