//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESKA_DI.Models._EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tx_IssueAndReceipt_Receipt_Item_Batch_Scale
    {
        public long DetDetDetId { get; set; }
        public Nullable<long> DetDetId { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string Uom { get; set; }
        public Nullable<decimal> Netto { get; set; }
        public Nullable<int> LineNum { get; set; }
        public string LineStatus { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> CreatedUser { get; set; }
        public Nullable<int> ModifiedUser { get; set; }
    }
}
