//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESKA_DI.Models._EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tx_IssueAndReceipt_Issue_Item
    {
        public long DetId { get; set; }
        public Nullable<long> Id { get; set; }
        public string ItemCode { get; set; }
        public string ItemName { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string Uom { get; set; }
        public string WhsCode { get; set; }
        public Nullable<decimal> Netto { get; set; }
        public string MsnPrd { get; set; }
        public string Cost { get; set; }
        public string Department { get; set; }
        public Nullable<long> DocEntry { get; set; }
        public Nullable<int> LineNum { get; set; }
        public string LineStatus { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> CreatedUser { get; set; }
        public Nullable<int> ModifiedUser { get; set; }
        public Nullable<int> QuantityCreated { get; set; }
    }
}
