//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BBS_DI.Models._EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tx_InventoryIn
    {
        public long Id { get; set; }
        public string TransType { get; set; }
        public string TransNo { get; set; }
        public Nullable<System.DateTime> TransDate { get; set; }
        public string Status { get; set; }
        public string VendorCode { get; set; }
        public string VendorName { get; set; }
        public string VendorRef { get; set; }
        public string WarehouseCode { get; set; }
        public string WarehouseName { get; set; }
        public string Remark { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedUser { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedUser { get; set; }
        public Nullable<int> Series { get; set; }
        public string SeriesName { get; set; }
        public Nullable<int> SapGrpoId { get; set; }
        public string SapGrpoNo { get; set; }
        public Nullable<int> SapPoId { get; set; }
        public string SapPoNo { get; set; }
        public string IsApproved { get; set; }
        public string IsAfterPosted { get; set; }
        public string ManBtchNum { get; set; }
        public string ShipCode { get; set; }
        public string Bagian { get; set; }
        public string ReqType { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<decimal> PotongaDp { get; set; }
        public Nullable<decimal> BiayaPengiriman { get; set; }
        public string Kategori { get; set; }
    }
}
