//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BBS_DI.Models._EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tx_Overhaul_GBKanan
    {
        public Nullable<long> Id { get; set; }
        public long DetId { get; set; }
        public Nullable<int> RowNum { get; set; }
        public string Item { get; set; }
        public string SubItem { get; set; }
        public string PartNumber { get; set; }
        public Nullable<decimal> QtyOrder { get; set; }
        public string Unit { get; set; }
        public string Cyl1 { get; set; }
        public string Cyl2 { get; set; }
        public string Cyl3 { get; set; }
        public string Cyl4 { get; set; }
        public string Cyl5 { get; set; }
        public string Cyl6 { get; set; }
        public string Cyl7 { get; set; }
        public string Cyl8 { get; set; }
        public string Cyl9 { get; set; }
        public string Cyl10 { get; set; }
        public string Cyl11 { get; set; }
        public string Cyl12 { get; set; }
        public string Cyl13 { get; set; }
        public string Cyl14 { get; set; }
        public string Cyl15 { get; set; }
        public string Cyl16 { get; set; }
        public Nullable<decimal> TotalRepair { get; set; }
        public Nullable<decimal> TotalReplace { get; set; }
        public string CleanNRepair { get; set; }
        public Nullable<decimal> QtySisa { get; set; }
        public string Remark { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedUser { get; set; }
        public Nullable<int> ModifiedUser { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string Status { get; set; }
    }
}
