//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESKA_DI.Models._EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tx_ProductionTask_Activity
    {
        public Nullable<long> Id { get; set; }
        public long DetId { get; set; }
        public Nullable<int> OperatorId { get; set; }
        public string OperatorName { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public string Batch { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public Nullable<long> TotalWorkDuration { get; set; }
        public Nullable<long> TotalPauseDuration { get; set; }
        public string Status { get; set; }
        public string Comments { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedUser { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedUser { get; set; }
        public Nullable<decimal> Netto { get; set; }
    }
}
