//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESKA_DI.Models._EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tx_ProductionTask
    {
        public long Id { get; set; }
        public string TransType { get; set; }
        public string TransNo { get; set; }
        public Nullable<long> BaseId { get; set; }
        public Nullable<long> BaseDetId { get; set; }
        public Nullable<int> DocEntry { get; set; }
        public string DocNum { get; set; }
        public string ItemCode { get; set; }
        public string ItemName { get; set; }
        public string Uom { get; set; }
        public Nullable<int> OperatorId { get; set; }
        public string OperatorName { get; set; }
        public Nullable<System.DateTime> PlannedDate { get; set; }
        public Nullable<System.DateTime> ActualDate { get; set; }
        public Nullable<decimal> QuantityPlanned { get; set; }
        public Nullable<decimal> QuantityActual { get; set; }
        public string IsRunningTask { get; set; }
        public Nullable<int> EstimatedHours { get; set; }
        public Nullable<int> ActualHours { get; set; }
        public string Status { get; set; }
        public string Comments { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedUser { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedUser { get; set; }
    }
}
