//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BBS_DI.Models._EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tx_Receipt
    {
        public long Id { get; set; }
        public string TransType { get; set; }
        public string TransNo { get; set; }
        public Nullable<System.DateTime> TransDate { get; set; }
        public Nullable<int> UnitId { get; set; }
        public string UnitName { get; set; }
        public Nullable<decimal> UnitCapacity { get; set; }
        public Nullable<int> DriverId { get; set; }
        public string DriverName { get; set; }
        public Nullable<decimal> QtyDelivery { get; set; }
        public Nullable<System.DateTime> ReceiptDate { get; set; }
        public Nullable<System.DateTime> LoadingDate { get; set; }
        public Nullable<System.DateTime> FinishDate { get; set; }
        public string T2DepanBelakang { get; set; }
        public Nullable<decimal> Temperature { get; set; }
        public Nullable<decimal> QtyReceipt { get; set; }
        public Nullable<System.DateTime> ReceiptTime { get; set; }
        public Nullable<System.DateTime> LoadingTime { get; set; }
        public Nullable<System.DateTime> FinishTime { get; set; }
        public Nullable<long> SuratJalanId { get; set; }
        public string SuratJalanNo { get; set; }
        public string Status { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedUser { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedUser { get; set; }
        public string ShippingType { get; set; }
        public Nullable<decimal> FlowMeterStart { get; set; }
        public Nullable<decimal> FlowMeterEnd { get; set; }
        public string UnitPoliceNo { get; set; }
    }
}
