//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BBS_DI.Models._EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tx_RunningHours_Daily
    {
        public Nullable<long> Id { get; set; }
        public long DetId { get; set; }
        public Nullable<int> RowNum { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<decimal> MEPS { get; set; }
        public Nullable<decimal> MESB { get; set; }
        public Nullable<decimal> AE1 { get; set; }
        public Nullable<decimal> AE2 { get; set; }
        public Nullable<decimal> GBME { get; set; }
        public Nullable<decimal> GBAE { get; set; }
        public string Remark { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedUser { get; set; }
        public Nullable<int> ModifiedUser { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}
