//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BBS_DI.Models._EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tx_RunningHours_Total
    {
        public Nullable<long> Id { get; set; }
        public long DetId { get; set; }
        public Nullable<int> RowNum { get; set; }
        public string Engine { get; set; }
        public Nullable<decimal> RunningHours { get; set; }
        public Nullable<decimal> LubOil { get; set; }
        public Nullable<decimal> LoFilter { get; set; }
        public Nullable<decimal> LoRacor { get; set; }
        public Nullable<decimal> FoFilter { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedUser { get; set; }
        public Nullable<int> ModifiedUser { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}
