//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BBS_DI.Models._EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tx_ShipInventory_Detail
    {
        public Nullable<long> Id { get; set; }
        public long DetId { get; set; }
        public string ItemCode { get; set; }
        public string ItemDescription { get; set; }
        public string Type { get; set; }
        public string UoMCode { get; set; }
        public Nullable<decimal> QtyUsed { get; set; }
        public Nullable<decimal> Stock { get; set; }
        public string Condition { get; set; }
        public Nullable<System.DateTime> LastReceivedDate { get; set; }
        public Nullable<decimal> QtyReceived { get; set; }
        public string Remark { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedUser { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedUser { get; set; }
    }
}
