//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESKA_DI.Models._EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tx_StockSummaryOpname_Ref
    {
        public Nullable<long> Id { get; set; }
        public long DetId { get; set; }
        public string BaseId { get; set; }
        public string BaseNo { get; set; }
        public string ScanDeviceId { get; set; }
        public string Comments { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> BaseCreatedDate { get; set; }
        public Nullable<int> BaseCreatedUser { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedUser { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedUser { get; set; }
    }
}
