//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BBS_DI.Models._EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tx_StockOpname
    {
        public long Id { get; set; }
        public string TransType { get; set; }
        public string TransNo { get; set; }
        public Nullable<System.DateTime> TransDate { get; set; }
        public Nullable<long> RequestId { get; set; }
        public string RequestNo { get; set; }
        public string WhsCode { get; set; }
        public string ScanDeviceId { get; set; }
        public string Status { get; set; }
        public string Comments { get; set; }
        public string CancelReason { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedUser { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedUser { get; set; }
    }
}
