//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BBS_DI.Models._EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tx_TransferIn_Item
    {
        public Nullable<long> Id { get; set; }
        public long DetId { get; set; }
        public Nullable<long> BaseEntry { get; set; }
        public Nullable<int> BaseLine { get; set; }
        public string BaseType { get; set; }
        public string ItemCode { get; set; }
        public string ItemName { get; set; }
        public string FromWhsCode { get; set; }
        public string FromWhsName { get; set; }
        public string ToWhsCode { get; set; }
        public string ToWhsName { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<decimal> QuantityOpen { get; set; }
        public Nullable<decimal> QuantityScan { get; set; }
        public Nullable<int> UomEntry { get; set; }
        public string Uom { get; set; }
        public string Comments { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedUser { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedUser { get; set; }
    }
}
