//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESKA_DI.Models._EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tx_TransferSummaryOut
    {
        public long Id { get; set; }
        public string TransType { get; set; }
        public string TransNo { get; set; }
        public Nullable<System.DateTime> TransDate { get; set; }
        public Nullable<System.DateTime> PostingDate { get; set; }
        public Nullable<long> DocEntry { get; set; }
        public string DocNum { get; set; }
        public Nullable<System.DateTime> DocDate { get; set; }
        public Nullable<long> RequestId { get; set; }
        public string RequestNo { get; set; }
        public string BaseType { get; set; }
        public string VendorCode { get; set; }
        public string VendorName { get; set; }
        public string Address { get; set; }
        public string FromWhsCode { get; set; }
        public string FromWhsName { get; set; }
        public string TransitWhsCode { get; set; }
        public string TransitWhsName { get; set; }
        public string ToWhsCode { get; set; }
        public string ToWhsName { get; set; }
        public Nullable<int> PriceList { get; set; }
        public string PriceListName { get; set; }
        public string ScanDeviceId { get; set; }
        public string Status { get; set; }
        public string ApprovalStatus { get; set; }
        public string IsAfterPosted { get; set; }
        public string Comments { get; set; }
        public string JournalRemarks { get; set; }
        public string CancelReason { get; set; }
        public string IsApproval { get; set; }
        public string ApprovalMessages { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedUser { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedUser { get; set; }
    }
}
