//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESKA_DI.Models._EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class WeighbridgeTransactions
    {
        public long Id { get; set; }
        public int WeightKg { get; set; }
        public string ScaleStatus { get; set; }
        public string ComPort { get; set; }
        public int BaudRate { get; set; }
        public string Message { get; set; }
        public System.DateTime SentAt { get; set; }
    }
}
